/* 7. SINIF — 1. Ünite: Sayılar ve Nicelikler (1), 2. Ünite: Geometrik Nicelikler (1) — Hafta 1-9 */
(function () {
  'use strict';
  var N = MC.num, Q = MC.Q, F = MC.frac;
  TEMAS.push({ id: 11, n: 1, grade: 7, title: 'Sayılar ve Nicelikler (1): Rasyonel Sayılar', hours: 25, color: '#8e44ad',
    summary: 'Sayı kümeleri, rasyonel sayılar, sayı doğrusu, mutlak değer, ondalık gösterim, dört işlem ve problemler.' });
  TEMAS.push({ id: 12, n: 2, grade: 7, title: 'Geometrik Nicelikler (1): Prizmalar', hours: 20, color: '#e17055',
    summary: 'Eş küplerle yapılar ve görünümler, dikdörtgenler prizmasının açınımı, yüzey alanı, hacmi ve birimleri.' });

  // ---- rasyonel yardımcıları (g7b.js de kullanır) ----
  function gcd(a, b) { a = Math.abs(a); b = Math.abs(b); return b ? gcd(b, a % b) : a; }
  function rd(n, d) { if (d < 0) { n = -n; d = -d; } var g = gcd(n, d) || 1; return [n / g, d / g]; }
  function sh(n, d) { if (d === undefined) d = 1; var x = rd(n, d); n = x[0]; d = x[1]; if (d === 1) return (n < 0 ? '−' : '') + Math.abs(n); return (n < 0 ? '−' : '') + F(Math.abs(n), d); }
  function key(x) { var y = rd(x[0], x[1]); return y[0] + '/' + y[1]; }
  function FQ(r, q, n, d, wr, exp) {
    var c = rd(n, d), seen = {}, w = []; seen[key(c)] = 1;
    wr.concat([[c[0] + 1, c[1]], [c[0] - 1, c[1]], [c[0], c[1] + 1], [-c[0], c[1]], [c[0] * 2, c[1]], [c[0] + c[1], c[1] * 2], [c[0] + 2, c[1]], [c[0], c[1] * 2 + 1], [c[0] + 3, c[1]]]).forEach(function (x) {
      if (x[1] === 0 || w.length >= 3) return; var k = key(x); if (!seen[k]) { seen[k] = 1; w.push(x); }
    });
    return Q(r, q, sh(c[0], c[1]), w.map(function (x) { return sh(x[0], x[1]); }), exp);
  }
  function rf(r, dlo, dhi) { var d, n; do { d = r.int(dlo || 2, dhi || 9); n = r.int(1, 9); } while (n % d === 0); return [n, d]; }
  function dec(x) { return N(Math.round(x * 1e6) / 1e6); }
  var bar = function (s) { return '<span style="text-decoration:overline">' + s + '</span>'; };

  function lineChart(labels, values, o) {
    o = o || {}; var lo = o.lo !== undefined ? o.lo : 0, hi = Math.ceil((o.hi || Math.max.apply(null, values)) / 4) * 4, W = 60 + labels.length * 56, H = 210, ph = 140;
    var s = MC.line(40, 20 + ph, W - 10, 20 + ph) + MC.line(40, 20, 40, 20 + ph), pts = [];
    for (var i = 0; i <= 4; i++) { var v = lo + (hi - lo) * i / 4, y = 20 + ph - ph * i / 4; s += MC.line(36, y, 40, y) + MC.txt(34, y + 4, N(Math.round(v * 10) / 10), { size: 11, anchor: 'end' }); }
    labels.forEach(function (l, i) { var x = 70 + i * 56, y = 20 + ph - ph * (values[i] - lo) / (hi - lo); pts.push(x + ',' + y); s += MC.txt(x, 20 + ph + 16, l, { size: 11 }); });
    s += '<polyline points="' + pts.join(' ') + '" fill="none" stroke="var(--brand)" stroke-width="3"/>';
    labels.forEach(function (l, i) { var x = 70 + i * 56, y = 20 + ph - ph * (values[i] - lo) / (hi - lo); s += '<circle cx="' + x + '" cy="' + y + '" r="5" class="dot"/>' + MC.txt(x, y - 10, N(values[i]), { size: 11 }); });
    return MC.svg(W, H, s, 'wide');
  }
  window.R7 = { gcd: gcd, rd: rd, sh: sh, FQ: FQ, rf: rf, dec: dec, key: key, lineChart: lineChart, bar: bar };

  function wk(tema, no, title, hours, outcomes, lesson, makers) {
    WEEKS.push({ grade: 7, tema: tema, no: 100 + no, wk: no, title: title, hours: hours, code: '', outcomes: outcomes,
      lesson: lesson.map(function (s) { return { h: s[0], html: s[1] }; }), makers: makers });
  }
  var DEF = function (t) { return '<div class="box def">' + t + '</div>'; };
  var EX = function (t) { return '<div class="box ex">' + t + '</div>'; };
  var TIP = function (t) { return '<div class="box tip">' + t + '</div>'; };
  var WARN = function (t) { return '<div class="box warn">' + t + '</div>'; };
  var ACT = function (t) { return '<div class="box idea"><b>Etkinlik:</b> ' + t + '</div>'; };

  // ============ HAFTA 1 ============
  wk(11, 1, 'Sayı Kümeleri, Rasyonel Sayılar ve Mutlak Değer', 6,
    ['Doğal sayılar, tam sayılar ve rasyonel sayılar arasındaki ilişkiyi açıklar.', 'Rasyonel sayıları sayı doğrusunda gösterir.', 'Bir rasyonel sayının mutlak değerini yorumlar.'],
    [['Ders Açılışı', '<p>Termometre, deniz seviyesi, banka hesabı… Hepsinde “eksi” sayılar var. Peki iki tam sayı arasında başka sayılar var mı? −1 ile 0 arasında hangi sayıları gösterebiliriz?</p>'],
     ['Sayı Kümeleri', DEF('<b>Sayma sayıları</b> {1, 2, 3, …} ⊂ <b>Doğal sayılar</b> {0, 1, 2, …} ⊂ <b>Tam sayılar</b> {…, −2, −1, 0, 1, 2, …} ⊂ <b>Rasyonel sayılar</b>') + '<p><b>Rasyonel sayı:</b> a ve b tam sayı, b ≠ 0 olmak üzere ' + F('a', 'b') + ' biçiminde yazılabilen sayılardır. Her tam sayı rasyoneldir (5 = ' + F(5, 1) + '). Paydası 0 olan ifade (' + F(3, 0) + ') <b>tanımsızdır</b>.</p>' + TIP('Rasyonel sayılar kümesi; tam sayıları, kesirleri, ondalık gösterimleri ve bunların negatiflerini içerir.')],
     ['Sayı Doğrusu', '<p>Negatif sayılar sıfırın solunda, pozitifler sağındadır. Sağdaki sayı soldakinden <b>büyüktür</b>.</p>' + EX('<b>Örnek:</b> −3 ile −2 arasındaki sayı: −2,5 = ' + sh(-5, 2) + '. Bir birimi 2 eş parçaya bölerseniz yarım noktaları bulursunuz.') + ACT('Yerde şerit metre ya da ip üzerinde sayı doğrusu yapın; çocuk −2, ' + sh(-1, 2) + ', 0, ' + sh(3, 4) + ' sayılarını işaretleyip üzerinde yürüsün.')],
     ['Mutlak Değer', DEF('Bir sayının sayı doğrusunda <b>0’a olan uzaklığına</b> mutlak değeri denir. |x| ile gösterilir; hiçbir zaman negatif olmaz.') + EX('|−7| = 7 &nbsp; |5| = 5 &nbsp; |0| = 0 &nbsp; |' + sh(-3, 4) + '| = ' + sh(3, 4) + '<br>|x| = 5 ise x = <b>5</b> veya <b>−5</b>.') + TIP('İki sayı arasındaki uzaklık = büyük sayı − küçük sayı. −3 ile 5 arası: 5 − (−3) = <b>8</b>.')]],
    [function (r) { var it = r.pick([[7, 'Sayma sayıları'], [0, 'Doğal sayılar'], [-4, 'Tam sayılar'], [sh(-2, 3), 'Rasyonel sayılar'], [sh(3, 5), 'Rasyonel sayılar']]); var names = ['Sayma sayıları', 'Doğal sayılar', 'Tam sayılar', 'Rasyonel sayılar']; return Q(r, N(it[0]) + ' sayısının ait olduğu <b>en dar</b> sayı kümesi hangisidir?', it[1], names.filter(function (x) { return x !== it[1]; }), 'En küçük küme: ' + it[1] + '.'); },
     function (r) { var k = r.int(2, 6); return Q(r, 'Aşağıdakilerden hangisi −' + k + ' ile −' + (k - 1) + ' arasındadır?', sh(-(2 * k - 1), 2), [sh(-(2 * k + 1), 2), sh(-(2 * k - 3), 2), sh(1, 2)], '−' + k + ' = ' + sh(-2 * k, 2) + ' ve −' + (k - 1) + ' = ' + sh(-(2 * k - 2), 2) + '; arası ' + sh(-(2 * k - 1), 2)); },
     function (r) { var a = r.int(3, 19); return Q(r, '|−' + a + '| kaçtır?', a, [-a, 0, a + 1], 'Mutlak değer 0’a uzaklıktır: ' + a); },
     function (r) { var a = r.int(3, 15), b = r.int(2, 12); return Q(r, '|−' + a + '| + |' + b + '| işleminin sonucu kaçtır?', a + b, [a - b, b - a, a * b], a + ' + ' + b + ' = ' + (a + b)); },
     function (r) { var v = r.sample([-9, -7, 4, 6, -3, 8, -12, 2], 4); var mx = v.slice().sort(function (x, y) { return Math.abs(y) - Math.abs(x); })[0]; return Q(r, 'Aşağıdaki sayılardan hangisinin mutlak değeri en büyüktür?', N(mx), v.filter(function (x) { return x !== mx; }).map(N), 'Mutlak değerler: ' + v.map(function (x) { return Math.abs(x); }).join(', ') + ' → en büyüğü ' + Math.abs(mx)); },
     function (r) { var a = r.int(2, 12), b = r.int(2, 12); return Q(r, 'Sayı doğrusunda −' + a + ' ile ' + b + ' arasındaki uzaklık kaç birimdir?', a + b, [Math.abs(a - b) || 1, a * b, a + b + 1], 'Uzaklık = ' + b + ' − (−' + a + ') = ' + (a + b)); },
     function (r) { var k = r.int(3, 20); return Q(r, '|x| = ' + k + ' denklemini sağlayan x değerleri hangileridir?', k + ' ve −' + k, [k + ' yalnızca', '−' + k + ' yalnızca', '0 ve ' + k], 'Uzaklığı ' + k + ' olan iki sayı vardır.'); },
     function (r) { return Q(r, 'Aşağıdakilerden hangisi rasyonel sayı <b>değildir</b>?', F(r.int(2, 9), 0), [F(0, r.int(2, 9)), F(r.int(1, 9), 7), sh(-r.int(2, 9), 1)], 'Paydası 0 olan ifade tanımsızdır.'); }]);

  // ============ HAFTA 2 ============
  wk(11, 2, 'Ondalık Gösterimler, Karşılaştırma ve Sıralama', 5,
    ['Rasyonel sayıların ondalık gösterimlerini sonlu ve devirli olarak ayırt eder.', 'Rasyonel sayıları karşılaştırır ve sıralar.'],
    [['Kesirden Ondalığa', '<p>Payı paydaya böleriz: ' + F(3, 8) + ' = 3 ÷ 8 = 0,375. Bölme ya <b>biter</b> (sonlu) ya da bir kalan tekrar eder (<b>devirli</b>).</p>' + DEF('<b>Sonlu:</b> ' + F(1, 4) + ' = 0,25 &nbsp;&nbsp; <b>Devirli:</b> ' + F(1, 3) + ' = 0,' + bar('3') + ' &nbsp; ' + F(5, 6) + ' = 0,8' + bar('3') + '<br>Devreden rakam(lar)ın üstüne çizgi çizilir.')],
     ['Sonlu mu, Devirli mi?', TIP('Kesri sadeleştirin. Paydası <b>yalnızca 2 ve 5</b> asal çarpanlarından oluşuyorsa ondalık gösterim <b>sonludur</b>. Paydada 3, 7, 11 gibi başka asal çarpan varsa <b>devirlidir</b>.') + EX(F(3, 20) + ' → 20 = 2·2·5 → sonlu (0,15)<br>' + F(5, 12) + ' → 12 = 2·2·3 → devirli (0,41' + bar('6') + ')<br>' + F(2, 7) + ' → devirli (0,' + bar('285714') + ')')],
     ['Devirli Ondalığı Kesre Çevirme', EX('0,' + bar('3') + ' = ' + F(3, 9) + ' = ' + F(1, 3) + ' &nbsp;&nbsp; 0,' + bar('5') + ' = ' + F(5, 9) + '<br>0,' + bar('27') + ' = ' + F(27, 99) + ' = ' + F(3, 11)) + ACT('Hesap makinesinde 1÷3, 2÷3, 1÷7, 1÷11 işlemlerini yaptırıp tekrar eden rakamları bulun.')],
     ['Karşılaştırma ve Sıralama', '<ul><li>Pozitif sayı > 0 > negatif sayı.</li><li>İki negatif sayıdan <b>mutlak değeri küçük olan büyüktür</b>: −2 > −5.</li><li>Kesirleri karşılaştırmak için paydaları eşitleyin veya ondalığa çevirin.</li></ul>' + EX('' + F(3, 4) + ' ile ' + F(5, 6) + ': paydalar 12 → ' + F(9, 12) + ' < ' + F(10, 12) + '<br>−' + F(2, 3) + ' ile −' + F(3, 4) + ': ' + F(8, 12) + ' < ' + F(9, 12) + ' → −' + F(2, 3) + ' > −' + F(3, 4))]],
    [function (r) { var d = r.pick([2, 4, 5, 8, 10, 20, 25]), n = r.int(1, d - 1); if (n % d === 0) n = 1; var x = rd(n, d); return Q(r, F(n, d) + ' kesrinin ondalık gösterimi aşağıdakilerden hangisidir?', dec(n / d), [dec(n / d * 10), dec(d / n), dec(n / d + 0.1)], 'Payı paydaya böl: ' + n + ' ÷ ' + d + ' = ' + dec(n / d)); },
     function (r) { var s = r.pick([[0.75, 3, 4], [0.6, 3, 5], [0.125, 1, 8], [0.4, 2, 5], [0.35, 7, 20], [0.8, 4, 5], [0.04, 1, 25]]); return FQ(r, dec(s[0]) + ' ondalık sayısının sadeleşmiş kesir karşılığı nedir?', s[1], s[2], [[s[0] * 100, 100], [s[1] + 1, s[2]]], dec(s[0]) + ' = ' + sh(s[0] * 1000, 1000) + ' = ' + sh(s[1], s[2])); },
     function (r) { var f = r.pick([[1, 3], [5, 12], [2, 7], [1, 6], [7, 15], [4, 9], [3, 8], [1, 5], [7, 20], [9, 11], [3, 4], [11, 25], [5, 6], [9, 16]]); var fin = (function (d) { while (d % 2 === 0) d /= 2; while (d % 5 === 0) d /= 5; return d === 1; })(f[1]); var c = fin ? 'Sonlu ondalık' : 'Devirli ondalık'; return Q(r, F(f[0], f[1]) + ' kesrinin ondalık gösterimi için aşağıdakilerden hangisi doğrudur?', c, ['Sonlu ondalık', 'Devirli ondalık', 'Tam sayı', 'Ondalık gösterimi yoktur'].filter(function (x) { return x !== c; }), 'Payda ' + f[1] + ' = ' + (fin ? 'yalnızca 2 ve 5 çarpanlı → sonlu' : 'başka asal çarpan içerir → devirli') + '.'); },
     function (r) { var k = r.int(1, 8); return FQ(r, '0,' + bar(k) + ' devirli ondalık sayısının kesir karşılığı nedir?', k, 9, [[k, 10], [k, 99], [k - 1 || 2, 9]], '0,' + bar(k) + ' = ' + F(k, 9)); },
     function (r) { var vs = []; var tries = 0; while (vs.length < 4 && tries++ < 100) { var f = rf(r, 2, 9), v = f[0] / f[1]; if (!vs.some(function (x) { return Math.abs(x[0] / x[1] - v) < 1e-9; })) vs.push(f); } var mx = vs.slice().sort(function (a, b) { return b[0] / b[1] - a[0] / a[1]; })[0]; return Q(r, 'Aşağıdaki sayılardan hangisi en büyüktür?', sh(mx[0], mx[1]), vs.filter(function (x) { return x !== mx; }).map(function (x) { return sh(x[0], x[1]); }), 'Ondalığa çevir: ' + vs.map(function (x) { return dec(Math.round(x[0] / x[1] * 100) / 100); }).join(', ') + ' (yaklaşık)'); },
     function (r) { var f = r.sample([[2, 3], [3, 4], [5, 6], [1, 2], [4, 5], [3, 5], [2, 7], [5, 8]], 3); var neg = f.map(function (x) { return [-x[0], x[1]]; }); var s = neg.slice().sort(function (a, b) { return a[0] / a[1] - b[0] / b[1]; }); var asc = s.map(function (x) { return sh(x[0], x[1]); }).join(' < '); var desc = s.slice().reverse().map(function (x) { return sh(x[0], x[1]); }).join(' < '); var sw = [s[1], s[0], s[2]].map(function (x) { return sh(x[0], x[1]); }).join(' < '); var sw2 = [s[0], s[2], s[1]].map(function (x) { return sh(x[0], x[1]); }).join(' < '); return Q(r, neg.map(function (x) { return sh(x[0], x[1]); }).join(' , ') + ' sayılarının küçükten büyüğe doğru sıralanışı hangisidir?', asc, [desc, sw, sw2], 'Negatiflerde mutlak değeri büyük olan daha küçüktür.'); },
     function (r) { var p = r.pick([[[1, 2], [3, 4], [5, 8]], [[1, 3], [1, 2], [2, 5]], [[2, 5], [3, 4], [1, 2]], [[1, 4], [1, 3], [3, 10]]]); return Q(r, F(p[0][0], p[0][1]) + ' ile ' + F(p[1][0], p[1][1]) + ' arasında yer alan sayı aşağıdakilerden hangisidir?', sh(p[2][0], p[2][1]), [sh(1, 5), sh(9, 10), sh(1, 8)].filter(function (x) { return true; }), dec(p[2][0] / p[2][1]) + ' sayısı ' + dec(p[0][0] / p[0][1]) + ' ile ' + dec(p[1][0] / p[1][1]) + ' arasındadır.'); },
     function (r) { var a = r.int(1, 8), b = r.int(1, 8), n = r.int(11, 30); var d = n % 2 ? a : b; return Q(r, '0,' + bar('' + a + b) + ' devirli ondalık sayısında virgülden sonraki ' + n + '. basamak hangi rakamdır?', d, [a === d ? b : a, 0, 9, (d + 1) % 10], 'Devir 2 basamaklı: tek sıralar ' + a + ', çift sıralar ' + b + '; ' + n + '. basamak ' + d + '.'); }]);

  // ============ HAFTA 3 ============
  wk(11, 3, 'Rasyonel Sayılarla Toplama ve Çıkarma', 5,
    ['Rasyonel sayılarla toplama ve çıkarma işlemlerini yapar.'],
    [['Ders Açılışı', '<p>Önce tam sayılarda toplama-çıkarmayı hatırlayın (−3 + 5 = 2; 4 − 7 = −3). Sıcaklık ve asansör örnekleriyle sayı doğrusunda “sağa/sola gitme” gösterilebilir.</p>'],
     ['Kural', DEF('<b>Paydalar eşitse</b> paylar toplanır/çıkarılır, payda aynen yazılır. <b>Paydalar farklıysa</b> önce paydalar eşitlenir (genişletme).') + EX(F(2, 5) + ' + ' + F(1, 3) + ' = ' + F(6, 15) + ' + ' + F(5, 15) + ' = ' + F(11, 15) + '<br>' + F(1, 4) + ' − ' + F(5, 6) + ' = ' + F(3, 12) + ' − ' + F(10, 12) + ' = −' + F(7, 12)) + WARN('Yanlış: ' + F(1, 2) + ' + ' + F(1, 3) + ' = ' + F(2, 5) + ' <b>değildir</b>! Paylar ve paydalar ayrı ayrı toplanmaz.')],
     ['İşaret Kuralları', '<ul><li>Eksi bir sayıyı çıkarmak, onun zıttını eklemektir: a − (−b) = a + b.</li><li>Zıt işaretli sayıları toplarken mutlak değerleri çıkarın, büyüğün işaretini yazın.</li></ul>' + EX('−' + F(3, 4) + ' + ' + F(1, 2) + ' = −' + F(3, 4) + ' + ' + F(2, 4) + ' = −' + F(1, 4) + '<br>−0,5 − (−1,25) = −0,5 + 1,25 = 0,75')],
     ['Etkinlik', ACT('Pizza kâğıt şeritlerle: 1 şeridi 12 eşit parçaya bölün; ' + F(1, 3) + ' ile ' + F(1, 4) + ' parçasını boyayıp toplamı sayarak paydaları eşitleme gereğini gösterin.')]],
    [function (r) { var d = r.int(5, 12), a = r.int(1, d - 2), b = r.int(1, d - a - 1); return FQ(r, F(a, d) + ' + ' + F(b, d) + ' işleminin sonucu nedir?', a + b, d, [[a + b, 2 * d]], 'Paydalar eşit: paylar toplanır → ' + sh(a + b, d)); },
     function (r) { var f = rf(r, 2, 9), g = rf(r, 2, 9); return FQ(r, F(f[0], f[1]) + ' + ' + F(g[0], g[1]) + ' işleminin sonucu nedir?', f[0] * g[1] + g[0] * f[1], f[1] * g[1], [[f[0] + g[0], f[1] + g[1]]], 'Paydaları eşitle: ' + sh(f[0] * g[1] + g[0] * f[1], f[1] * g[1])); },
     function (r) { var f = rf(r, 2, 9), g = rf(r, 2, 9); return FQ(r, F(f[0], f[1]) + ' − ' + F(g[0], g[1]) + ' işleminin sonucu nedir?', f[0] * g[1] - g[0] * f[1], f[1] * g[1], [[f[0] - g[0], f[1] - g[1] || 1]], 'Paydaları eşitle: ' + sh(f[0] * g[1] - g[0] * f[1], f[1] * g[1])); },
     function (r) { var a = r.int(1, 30) / 10, b = r.int(11, 40) / 10; var res = Math.round((-a + b) * 100) / 100; return Q(r, '−' + dec(a) + ' + ' + dec(b) + ' işleminin sonucu kaçtır?', dec(res), [dec(res + 0.1), dec(-res), dec(a + b)], '−' + dec(a) + ' + ' + dec(b) + ' = ' + dec(res)); },
     function (r) { var f = rf(r, 2, 6), k = r.int(2, 5); return FQ(r, k + ' − ' + F(f[0], f[1]) + ' işleminin sonucu nedir?', k * f[1] - f[0], f[1], [[k - f[0], f[1]]], k + ' = ' + sh(k * f[1], f[1]) + ' → ' + sh(k * f[1] - f[0], f[1])); },
     function (r) { var x = rf(r, 2, 9), y = rf(r, 2, 9); return FQ(r, 'x + ' + F(x[0], x[1]) + ' = ' + F(y[0], y[1]) + ' ise x kaçtır?', y[0] * x[1] - x[0] * y[1], x[1] * y[1], [[y[0] + x[0], y[1]], [y[0] - x[0], y[1]]], 'x = ' + F(y[0], y[1]) + ' − ' + F(x[0], x[1])); },
     function (r) { var f = rf(r, 3, 9), g = rf(r, 2, 9); if (f[0] / f[1] + g[0] / g[1] >= 1) { f = [1, 3]; g = [1, 4]; } return FQ(r, 'Bir su deposunun ' + F(f[0], f[1]) + '’i dolu iken ' + F(g[0], g[1]) + '’i kadar daha su ekleniyor. Deponun kaçta kaçı dolu olur?', f[0] * g[1] + g[0] * f[1], f[1] * g[1], [[f[0] + g[0], f[1] + g[1]]], sh(f[0], f[1]) + ' + ' + sh(g[0], g[1]) + ' = ' + sh(f[0] * g[1] + g[0] * f[1], f[1] * g[1])); },
     function (r) { var f = rf(r, 2, 9), g = rf(r, 2, 9); return FQ(r, '−' + F(f[0], f[1]) + ' − (−' + F(g[0], g[1]) + ') işleminin sonucu nedir?', -f[0] * g[1] + g[0] * f[1], f[1] * g[1], [[-f[0] - g[0], f[1] * g[1]]], 'Eksi bir sayıyı çıkarmak, zıttını eklemektir: −' + sh(f[0], f[1]) + ' + ' + sh(g[0], g[1])); }]);

  // ============ HAFTA 4 ============
  wk(11, 4, 'Rasyonel Sayılarla Çarpma ve Bölme', 5,
    ['Rasyonel sayılarla çarpma ve bölme işlemlerini yapar.'],
    [['Ders Açılışı', '<p>Yarım pizzanın üçte biri ne kadar? Kâğıt katlama ile ' + F(1, 2) + ' × ' + F(1, 3) + ' = ' + F(1, 6) + ' gösterilir.</p>'],
     ['Çarpma', DEF('Paylar çarpılır, paydalar çarpılır: ' + F('a', 'b') + ' · ' + F('c', 'd') + ' = ' + F('a·c', 'b·d') + '. Sadeleştirme çarpmadan önce de yapılabilir.') + EX(F(2, 3) + ' · ' + F(9, 10) + ' = ' + F('2·9', '3·10') + ' = ' + F(3, 5) + '<br>' + F(-2, 5) + ' · ' + F(-5, 6) + ' = ' + F(1, 3) + ' (iki eksi → artı)')],
     ['Bölme', DEF('İlk kesir aynen yazılır, ikinci kesrin <b>çarpmaya göre tersi</b> ile çarpılır.') + EX(F(3, 4) + ' ÷ ' + F(3, 8) + ' = ' + F(3, 4) + ' · ' + F(8, 3) + ' = 2<br>−' + F(5, 6) + ' sayısının çarpmaya göre tersi: −' + F(6, 5)) + TIP('İşaretler: aynı işaretli iki sayının çarpımı/bölümü <b>pozitif</b>, zıt işaretlilerinki <b>negatif</b>.')],
     ['Bir Sayının Kesri', EX('40 TL’nin ' + F(3, 5) + '’i = 40 · ' + F(3, 5) + ' = <b>24 TL</b><br>' + F(3, 4) + ' litre suyu ' + F(1, 8) + ' litrelik bardaklara bölersek: ' + F(3, 4) + ' ÷ ' + F(1, 8) + ' = <b>6 bardak</b>')]],
    [function (r) { var f = rf(r, 2, 9), g = rf(r, 2, 9); return FQ(r, F(f[0], f[1]) + ' · ' + F(g[0], g[1]) + ' işleminin sonucu nedir?', f[0] * g[0], f[1] * g[1], [[f[0] + g[0], f[1] + g[1]]], 'Paylar ve paydalar çarpılır → ' + sh(f[0] * g[0], f[1] * g[1])); },
     function (r) { var f = rf(r, 2, 9), g = rf(r, 2, 9); return FQ(r, F(f[0], f[1]) + ' ÷ ' + F(g[0], g[1]) + ' işleminin sonucu nedir?', f[0] * g[1], f[1] * g[0], [[f[0] * g[0], f[1] * g[1]]], 'İkinci kesrin tersiyle çarpılır: ' + sh(f[0], f[1]) + ' · ' + sh(g[1], g[0])); },
     function (r) { var f = rf(r, 2, 6), k = r.int(2, 8); return FQ(r, k + ' · ' + F(f[0], f[1]) + ' işleminin sonucu nedir?', k * f[0], f[1], [[k + f[0], f[1]]], k + ' · ' + sh(f[0], f[1]) + ' = ' + sh(k * f[0], f[1])); },
     function (r) { var f = rf(r, 2, 9), g = rf(r, 2, 9); return FQ(r, '−' + F(f[0], f[1]) + ' · (−' + F(g[0], g[1]) + ') işleminin sonucu nedir?', f[0] * g[0], f[1] * g[1], [[-f[0] * g[0], f[1] * g[1]]], 'İki negatifin çarpımı pozitiftir.'); },
     function (r) { var a = r.pick([2.5, 1.5, 0.5, 3.5, 4.5]), b = r.pick([0.4, 0.2, 0.6, 0.8]); var v = Math.round(a * b * 100) / 100; return Q(r, a >= 0 ? dec(a) + ' · (−' + dec(b) + ') işleminin sonucu kaçtır?' : '', '−' + dec(v), [dec(v), '−' + dec(v * 10), '−' + dec(v / 10)], 'Zıt işaretli çarpım negatiftir: ' + dec(a) + ' · ' + dec(b) + ' = ' + dec(v)); },
     function (r) { var f = rf(r, 2, 9); return FQ(r, '−' + F(f[0], f[1]) + ' sayısının çarpmaya göre tersi aşağıdakilerden hangisidir?', -f[1], f[0], [[f[1], f[0]], [f[0], f[1]]], 'Tersi için pay ve payda yer değiştirir, işaret aynı kalır.'); },
     function (r) { var d = r.pick([4, 5, 8, 10]), n = r.int(1, d - 1), P = d * r.int(4, 10); return Q(r, P + ' TL’nin ' + F(n, d) + '’i kaç TL’dir?', N(P * n / d), [N(P * n / d + n), N(P / n), N(P + n)], P + ' · ' + sh(n, d) + ' = ' + N(P * n / d)); },
     function (r) { var k = r.int(2, 6), d = r.pick([2, 4, 5, 8]); var tot = k * d * r.int(1, 3); return Q(r, tot / d * 1 + ' litre suyu ' + F(1, d) + ' litrelik bardaklara bölersek kaç bardak gerekir?', N(tot), [N(tot / d), N(tot + 1), N(tot * d)], (tot / d) + ' ÷ ' + sh(1, d) + ' = ' + (tot / d) + ' · ' + d + ' = ' + tot); }]);

  // ============ HAFTA 5 ============
  wk(11, 5, 'Rasyonel Sayılarla İlgili Problemler', 4,
    ['Rasyonel sayılarla ilgili problemleri çözer.'],
    [['Problem Çözme Adımları', '<ol><li>Problemi oku, ne istendiğini altını çizerek bul.</li><li>Şemayla göster (şerit modeli, kesir çubuğu).</li><li>İşlemi seç: “’i/’si” → çarpma; “eşit paylaştır / kaç tane sığar” → bölme.</li><li>Sonucu kontrol et: mantıklı mı?</li></ol>'],
     ['Çözümlü Örnek 1', EX('Bir sayının ' + F(2, 3) + '’si 24 ise sayı kaçtır?<br><b>Çözüm:</b> ' + F(2, 3) + ' → 24 ise ' + F(1, 3) + ' → 12, tamamı = 3·12 = <b>36</b>.')],
     ['Çözümlü Örnek 2', EX('Ali parasının ' + F(1, 3) + '’i ile kitap, kalanın ' + F(1, 2) + '’si ile defter aldı. Geriye 20 TL kaldı. İlk parası?<br><b>Çözüm:</b> Kitaptan sonra ' + F(2, 3) + ' kalır. Defterden sonra ' + F(2, 3) + ' · ' + F(1, 2) + ' = ' + F(1, 3) + ' kalır. ' + F(1, 3) + ' = 20 TL → parası <b>60 TL</b>.')],
     ['Etkinlik', ACT('Şerit modeliyle “Ayşe kitabın ' + F(2, 5) + '’ini ilk gün okudu” problemini çizdirin; her parçaya kaç sayfa düştüğünü bulduktan sonra işlemi yazdırın.')]],
    [function (r) { var d = r.pick([3, 4, 5, 6]), n = r.int(1, d - 1), u = r.int(3, 9); var x = u * d, part = u * n; return Q(r, 'Bir sayının ' + F(n, d) + '’i ' + part + ' ise bu sayı kaçtır?', x, [x + u, part * 2, part + d], F(1, d) + '’i ' + u + ' → tamamı ' + u + ' · ' + d + ' = ' + x); },
     function (r) { var c = r.pick([[[1, 3], [1, 2], [1, 3]], [[1, 4], [1, 3], [1, 2]], [[1, 5], [1, 4], [3, 5]], [[1, 3], [1, 4], [1, 2]]]); var P = 60 * r.int(1, 3); var left = P * c[2][0] / c[2][1]; return Q(r, 'Bir kişi parasının ' + F(c[0][0], c[0][1]) + ' kadarını harcıyor, kalanın ' + F(c[1][0], c[1][1]) + ' kadarını da harcıyor. Geriye ' + left + ' TL kalıyor. Başlangıçtaki parası kaç TL’dir?', P, [N(left * 2), N(P + 20), N(left + P / 2)], 'Kalan kesir ' + sh(c[2][0], c[2][1]) + '; ' + left + ' ÷ ' + sh(c[2][0], c[2][1]) + ' = ' + P); },
     function (r) { var t = r.pick([[-3.5, 6.25], [-8, 4.5], [-2.75, 5], [-6, 2.5]]); var res = Math.round((t[0] + t[1]) * 100) / 100; return Q(r, 'Sabah sıcaklık ' + dec(t[0]) + '°C iken öğlene kadar ' + dec(t[1]) + '°C artıyor. Öğlen sıcaklığı kaç °C olur?', dec(res), [dec(res + 1), dec(-res), dec(t[1] - t[0])], dec(t[0]) + ' + ' + dec(t[1]) + ' = ' + dec(res)); },
     function (r) { var tot = r.pick([120, 180, 240]), a = r.pick([[2, 5], [1, 3], [1, 4]]); var day1 = tot * a[0] / a[1], rem = tot - day1; var day2 = rem / 3; if (day2 !== Math.floor(day2)) return Q(r, 'Bir kitap ' + tot + ' sayfadır. İlk gün ' + F(a[0], a[1]) + '’i okunursa kaç sayfa okunmamış kalır?', N(rem), [N(day1), N(rem + 10), N(tot / 2)], tot + ' − ' + day1 + ' = ' + rem); return Q(r, 'Bir kitap ' + tot + ' sayfadır. İlk gün ' + F(a[0], a[1]) + '’i, ikinci gün kalanın ' + F(1, 3) + '’i okunuyor. Kaç sayfa kalır?', N(rem - day2), [N(rem), N(day1 + day2), N(rem - day2 + 10)], 'İlk gün ' + day1 + ', kalan ' + rem + ', ikinci gün ' + day2 + ' → ' + (rem - day2)); },
     function (r) { var d = r.pick([3, 5, 4]), n = d - 1, full = d * r.int(10, 30); var have = full * n / d; return Q(r, 'Bir su deposunun ' + F(n, d) + '’i ' + have + ' litredir. Deponun tamamen dolması için kaç litre su eksiktir?', N(full - have), [N(have), N(full), N(full - have + d)], 'Tamamı ' + full + ' L; eksik ' + (full - have) + ' L.'); },
     function (r) { var a = r.pick([[2.25, 0.75], [3, 0.5], [4.5, 1.5], [6, 0.75]]); return Q(r, dec(a[0]) + ' metre kumaş ' + dec(a[1]) + ' metrelik parçalara bölünüyor. Kaç parça elde edilir?', N(a[0] / a[1]), [N(a[0] / a[1] + 1), N(a[0] * a[1]), N(a[0] / a[1] - 1)], dec(a[0]) + ' ÷ ' + dec(a[1]) + ' = ' + N(a[0] / a[1])); },
     function (r) { var f = r.pick([[-1, 2], [-3, 4], [-2, 3]]), g = r.pick([[3, 4], [1, 2], [5, 6]]); var d = Math.abs(g[0] / g[1] - f[0] / f[1]); var n = g[0] * f[1] - f[0] * g[1], dd = g[1] * f[1]; return FQ(r, 'Sayı doğrusunda ' + sh(f[0], f[1]) + ' ile ' + sh(g[0], g[1]) + ' arasındaki uzaklık kaç birimdir?', n, dd, [[g[0] - f[0], g[1] - f[1] || 1], [Math.abs(g[0] * f[1] + f[0] * g[1]), dd]], 'Uzaklık = büyük − küçük = ' + sh(g[0], g[1]) + ' − (' + sh(f[0], f[1]) + ')'); }]);

  // ============ HAFTA 6 ============
  function H3(r) { var H = []; for (var i = 0; i < 3; i++) { H.push([]); for (var j = 0; j < 3; j++) H[i].push(r.pick([0, 1, 1, 2, 2, 3])); } if (!H.some(function (row) { return row.some(function (x) { return x > 0; }); })) H[1][1] = 2; return H; }
  function topTable(H) { return '<table class="tbl"><tbody>' + H.map(function (row) { return '<tr>' + row.map(function (x) { return '<td style="min-width:42px;text-align:center">' + (x || '·') + '</td>'; }).join('') + '</tr>'; }).join('') + '</tbody></table><p class="note">Üstten görünüm: sayılar o karedeki küp sayısıdır. Üst satır arka, alt satır ön taraftır.</p>'; }
  function frontView(H) { var f = []; for (var c = 0; c < 3; c++) f.push(Math.max(H[0][c], H[1][c], H[2][c])); return f; }
  function sideView(H) { var s = []; for (var i = 2; i >= 0; i--) s.push(Math.max.apply(null, H[i])); return s; }
  wk(12, 6, 'Eş Küplerle Yapılar ve Üç Görünüm', 5,
    ['Eş küplerle oluşturulan yapıların önden, yandan ve üstten görünümlerini çizer ve yorumlar.', 'Görünümleri verilen yapıyı eş küplerle oluşturur.'],
    [['Ders Açılışı', '<p>Lego ya da şeker küpleriyle bir yapı kurun. Masanın karşısından, yanından ve tepeden bakınca ne görüyorsunuz? Üç bakış açısı ne kadar farklı çıkıyor?</p>' + ACT('Çocuk 8–10 küple bir yapı kursun; sonra siz sadece üç görünümü çizin; çocuk aynı yapıyı kurmaya çalışsın.')],
     ['Üç Görünüm', '<ul><li><b>Önden görünüm:</b> Karşıdan bakınca her sütunda <b>en yüksek</b> küp sayısı görünür.</li><li><b>Yandan görünüm:</b> Yan taraftan bakınca her sırada en yüksek küp sayısı görünür.</li><li><b>Üstten görünüm:</b> Tepeden bakınca küplerin kapladığı kareler görünür. Her karenin üstüne o yığındaki küp sayısını yazarak yapıyı tam anlatabiliriz.</li></ul>' + EX('Üstten görünüm sayıları:<br>' + topTable([[2, 0, 1], [1, 3, 0], [0, 1, 2]]) + 'Küp sayısı = 2+1+1+3+1+2 = <b>10</b>. Önden bakınca (soldan sağa) en yüksek sütunlar: 2, 3, 2.')],
     ['Görünümden Yapıya', TIP('Önden ve yandan görünümleri verilen bir yapıda, her kare için <b>en fazla</b> min(önden sütun yüksekliği, yandan sıra yüksekliği) kadar küp olabilir. En fazla küp sayısı bu değerlerin toplamıdır. Görünümleri sağlayan birden fazla yapı olabilir.')],
     ['Kutu Hatırlatması', EX('3 × 2 × 4’lük bir dikdörtgenler prizması 3·2·4 = <b>24</b> küpten oluşur.')]],
    [function (r) { var H = H3(r); var s = 0; H.forEach(function (row) { s += row.reduce(function (a, b) { return a + b; }, 0); }); return Q(r, 'Aşağıda bir yapının üstten görünümü verilmiştir (sayılar küp sayısıdır). Yapı kaç küpten oluşur?<br>' + topTable(H), s, [s + 1, s - 1 > 0 ? s - 1 : s + 4, s + 2], 'Sayıları topla: ' + s); },
     function (r) { var H = H3(r); var f = frontView(H); var cs = f.join(', '); var wrong = [[f[1], f[0], f[2]], [f[2], f[1], f[0]], [Math.min.apply(null, f), Math.max.apply(null, f), f[1]]].map(function (x) { return x.join(', '); }); return Q(r, 'Üstten görünümü verilen yapının <b>önden görünümünde</b> soldan sağa sütun yükseklikleri nelerdir?<br>' + topTable(H), cs, wrong.concat([(f[0] + 1) + ', ' + f[1] + ', ' + f[2]]), 'Her sütunda en yüksek değer: ' + cs); },
     function (r) { var H = H3(r); var s = sideView(H); var cs = s.join(', '); return Q(r, 'Üstten görünümü verilen yapının <b>sağ yandan görünümünde</b> soldan sağa (ön sıradan arka sıraya) yükseklikler nelerdir?<br>' + topTable(H), cs, [s.slice().reverse().join(', '), frontView(H).join(', '), (s[0] + 1) + ', ' + s[1] + ', ' + s[2]], 'Her satırdaki en yüksek değer, ön satırdan başlayarak: ' + cs); },
     function (r) { var H = H3(r); var c = 0; H.forEach(function (row) { row.forEach(function (x) { if (x > 0) c++; }); }); return Q(r, 'Üstten görünümü verilen yapıda üstten bakıldığında kaç kare görünür?<br>' + topTable(H), c, [c + 1, c - 1 > 0 ? c - 1 : c + 3, 9], 'Küp olan (0’dan büyük) kareleri say: ' + c); },
     function (r) { var f = [r.int(1, 3), r.int(1, 3), r.int(1, 3)], s = [r.int(1, 3), r.int(1, 3), r.int(1, 3)]; var mx = 0; for (var i = 0; i < 3; i++) for (var j = 0; j < 3; j++) mx += Math.min(f[j], s[i]); return Q(r, 'Bir yapının önden görünümünde sütun yükseklikleri (soldan sağa) ' + f.join(', ') + ', yandan görünümünde sıra yükseklikleri ' + s.join(', ') + ' dir. Bu yapı <b>en fazla</b> kaç küpten oluşabilir?', mx, [mx + 1, mx - 1 > 0 ? mx - 1 : mx + 3, mx + 2], 'Her kare için min(sütun, sıra) toplanır = ' + mx); },
     function (r) { var a = r.int(2, 5), b = r.int(2, 4), c = r.int(2, 4); return Q(r, 'Boyutları ' + a + ' × ' + b + ' × ' + c + ' küp olan bir dikdörtgenler prizması kaç eş küpten oluşur?', a * b * c, [a + b + c, a * b * c + a, 2 * (a * b + b * c + a * c)], a + ' · ' + b + ' · ' + c + ' = ' + a * b * c); },
     function (r) { var n = r.int(3, 8); return Q(r, 'Üst üste dizilmiş ' + n + ' eş küpten oluşan bir sütunun tamamı (alt yüzü dâhil) boyanırsa kaç küp yüzü boyanır?', 4 * n + 2, [4 * n, 6 * n, 4 * n + 1], 'Yan yüzler 4n + üst 1 + alt 1 = ' + (4 * n + 2)); },
     function (r) { var H = H3(r); return Q(r, 'Üstten görünümü verilen yapıda kaç tane kare <b>2 veya daha fazla</b> küp yüksekliğindedir?<br>' + topTable(H), H.reduce(function (a, row) { return a + row.filter(function (x) { return x >= 2; }).length; }, 0), [0, 1, 2, 3, 4, 5, 6].filter(function (v) { return v !== H.reduce(function (a, row) { return a + row.filter(function (x) { return x >= 2; }).length; }, 0); }).slice(0, 4), 'Sayıları kontrol et.'); }]);

  // ============ HAFTA 7 ============
  function netFig() {
    var u = 36, s = '';
    function rect(x, y, w, h, t) { return '<rect x="' + x + '" y="' + y + '" width="' + w + '" height="' + h + '" class="shape"/>' + MC.txt(x + w / 2, y + h / 2 + 5, t, { size: 13 }); }
    s += rect(20 + 90, 10, 90, 54, 'Üst');
    s += rect(20, 64, 90, 72, 'Sol') + rect(110, 64, 90, 72, 'Ön') + rect(200, 64, 90, 72, 'Sağ') + rect(290, 64, 90, 72, 'Arka');
    s += rect(20 + 90, 136, 90, 54, 'Alt');
    return MC.svg(400, 200, s, 'wide');
  }
  wk(12, 7, 'Dikdörtgenler Prizmasının Açınımı ve Yüzey Alanı', 5,
    ['Dikdörtgenler prizmasının açınımını çizer ve inceler.', 'Dikdörtgenler prizmasının yüzey alanını hesaplar.'],
    [['Ders Açılışı', '<p>Boş bir bisküvi kutusunu dikkatle açıp düz masaya serin. Gördüğünüz şekil <b>açınımdır</b>. Kutuyu geri katlarsanız prizma olur.</p>' + ACT('Kutuyu keserek açınımı elde edin; her yüzün hangi yüze karşılık geldiğini renklendirin.')],
     ['Açınım', '<p>Dikdörtgenler prizmasının <b>6 yüzü</b> vardır; <b>karşılıklı yüzler eştir</b> (3 çift).</p>' + netFig() + '<p class="note">Bir prizmanın birden fazla farklı açınımı olabilir.</p>'],
     ['Yüzey Alanı', DEF('Tüm yüzlerin alanları toplamıdır. Ayrıtları a, b, c olan prizmanın yüzey alanı: <b>2·(a·b + a·c + b·c)</b><br>Küpün yüzey alanı: <b>6a²</b>') + EX('3 × 4 × 5 cm’lik prizma: 2·(12 + 15 + 20) = 2·47 = <b>94 cm²</b>.<br>Kenarı 5 cm olan küp: 6·25 = <b>150 cm²</b>.') + WARN('Yüzey alanı <b>cm²</b>, hacim <b>cm³</b> ile ölçülür. Birimleri karıştırmayın!')],
     ['Üstü Açık Kutu', TIP('Üstü açık bir kutunun yüzey alanı = 2·(ab + ac + bc) − (üst yüzün alanı). Örnek: 4 × 3 × 2 cm kutu, üstü açık: 2·(12+8+6) − 12 = <b>40 cm²</b>.')]],
    [function (r) { var a = r.int(2, 8), b = r.int(2, 8), c = r.int(2, 8); var s = 2 * (a * b + a * c + b * c); return Q(r, 'Ayrıtları ' + a + ' cm, ' + b + ' cm ve ' + c + ' cm olan dikdörtgenler prizmasının yüzey alanı kaç cm²’dir?', s, [a * b * c, s / 2, s + 2 * a], '2·(' + a * b + ' + ' + a * c + ' + ' + b * c + ') = ' + s); },
     function (r) { var a = r.int(2, 12); return Q(r, 'Bir ayrıtı ' + a + ' cm olan küpün yüzey alanı kaç cm²’dir?', 6 * a * a, [a * a * a, 4 * a * a, 6 * a], '6 · ' + a + ' · ' + a + ' = ' + 6 * a * a); },
     function (r) { var a = r.int(2, 9); return Q(r, 'Yüzey alanı ' + 6 * a * a + ' cm² olan bir küpün bir ayrıtı kaç cm’dir?', a, [a + 1, a - 1 || 2, a * 2], '6a² = ' + 6 * a * a + ' → a² = ' + a * a + ' → a = ' + a); },
     function (r) { return Q(r, 'Bir dikdörtgenler prizmasının açınımı kaç tane dikdörtgenden oluşur?', 6, [4, 5, 8], 'Prizmanın 6 yüzü vardır.'); },
     function (r) { return Q(r, 'Bir dikdörtgenler prizmasında eş yüzler kaç çift oluşturur?', 3, [2, 4, 6], 'Karşılıklı yüzler eştir: 3 çift.'); },
     function (r) { var a = r.int(2, 7), b = r.int(2, 6), c = r.int(2, 6); return Q(r, 'Ayrıtları ' + a + ' cm, ' + b + ' cm ve ' + c + ' cm olan, <b>üstü açık</b> bir kutunun yüzey alanı (üst yüz yok) kaç cm²’dir? (Taban ' + a + ' × ' + b + ' cm)', 2 * (a * b + a * c + b * c) - a * b, [2 * (a * b + a * c + b * c), a * b + 2 * a * c + 2 * b * c + a * b, a * b * c], 'Yüzey alanından üst yüzün alanı (' + a * b + ') çıkarılır.'); },
     function (r) { var x = r.pick([[3, 4, 5], [2, 3, 6], [2, 4, 5], [3, 3, 4], [2, 5, 6]]); var ab = x[0] * x[1], ac = x[0] * x[2], bc = x[1] * x[2]; return Q(r, 'Üç farklı yüzünün alanları ' + ab + ' cm², ' + ac + ' cm² ve ' + bc + ' cm² olan dikdörtgenler prizmasının yüzey alanı kaç cm²’dir?', 2 * (ab + ac + bc), [ab + ac + bc, 3 * (ab + ac + bc), 2 * (ab + ac + bc) - ab], 'Üç farklı yüz toplamının 2 katı: 2·(' + ab + ' + ' + ac + ' + ' + bc + ')'); },
     function (r) { var a = r.int(4, 10), b = r.int(3, 8), c = r.int(2, 6), p = r.pick([2, 3, 5]); var s = 2 * (a * b + a * c + b * c); return Q(r, a + ' × ' + b + ' × ' + c + ' cm boyutlarındaki bir kutunun tamamı bir kâğıtla kaplanacak. Kâğıdın cm² başına maliyeti ' + p + ' kuruş ise toplam maliyet kaç kuruştur?', s * p, [s, a * b * c * p, s * p / 2], 'Yüzey alanı ' + s + ' cm² → ' + s + ' · ' + p + ' = ' + s * p); }]);

  // ============ HAFTA 8 ============
  wk(12, 8, 'Hacim ve Hacim Ölçme Birimleri', 5,
    ['Dikdörtgenler prizmasının hacmini hesaplar.', 'Hacim ölçme birimleri arasında dönüşüm yapar.'],
    [['Ders Açılışı', '<p>Bir kutuya kaç küp sığar? Kenarı 1 cm olan birim küplerle 4×3×2’lik bir kutuyu doldurun ve sayın.</p>'],
     ['Hacim', DEF('Bir cismin uzayda kapladığı yere <b>hacim</b> denir. Dikdörtgenler prizmasının hacmi: <b>V = a · b · c = taban alanı × yükseklik</b>. Küpün hacmi: <b>a³</b>.') + EX('4 × 3 × 2 cm: V = 24 cm³ (24 birim küp).<br>Kenarı 5 cm olan küp: V = 5³ = <b>125 cm³</b>.') + TIP('Her ayrıt 2 katına çıkarsa hacim <b>8 katına</b> çıkar (2·2·2).')],
     ['Hacim Ölçme Birimleri', DEF('km³ → hm³ → dam³ → m³ → dm³ → cm³ → mm³: her basamak <b>1000</b> katıdır.<br>1 m³ = 1000 dm³ &nbsp; 1 dm³ = 1000 cm³ &nbsp; <b>1 dm³ = 1 litre</b> &nbsp; 1 cm³ = 1 mL') + EX('3 m³ = 3000 dm³ &nbsp; 5000 cm³ = 5 dm³ = 5 L &nbsp; 2,5 dm³ = 2500 cm³')],
     ['Etkinlik', ACT('1 litrelik süt kutusu ile 10×10×10 cm’lik şeffaf bir kutuyu karşılaştırın; 1 L = 1 dm³ = 1000 cm³ olduğunu su dolduraraktan gösterin.')]],
    [function (r) { var a = r.int(2, 9), b = r.int(2, 9), c = r.int(2, 9); return Q(r, 'Ayrıtları ' + a + ' cm, ' + b + ' cm ve ' + c + ' cm olan dikdörtgenler prizmasının hacmi kaç cm³’tür?', a * b * c, [a + b + c, 2 * (a * b + b * c + a * c), a * b * c + a], a + ' · ' + b + ' · ' + c + ' = ' + a * b * c); },
     function (r) { var a = r.int(2, 10); return Q(r, 'Bir ayrıtı ' + a + ' cm olan küpün hacmi kaç cm³’tür?', a * a * a, [6 * a * a, 3 * a, a * a], a + '³ = ' + a * a * a); },
     function (r) { var t = r.int(8, 40), h = r.int(2, 9); return Q(r, 'Taban alanı ' + t + ' cm² ve yüksekliği ' + h + ' cm olan dikdörtgenler prizmasının hacmi kaç cm³’tür?', t * h, [t + h, t * h / 2, 2 * t * h], 'V = taban alanı · yükseklik = ' + t * h); },
     function (r) { var a = r.int(3, 8), b = r.int(2, 6), c = r.int(2, 9); var v = a * b * c; return Q(r, 'Hacmi ' + v + ' cm³, iki ayrıtı ' + a + ' cm ve ' + b + ' cm olan dikdörtgenler prizmasının üçüncü ayrıtı kaç cm’dir?', c, [c + 1, c - 1 || 2, a + b], v + ' ÷ (' + a + ' · ' + b + ') = ' + c); },
     function (r) { var t = r.pick([[3, 'm³', 'dm³', 3000], [7, 'm³', 'dm³', 7000], [2, 'dm³', 'cm³', 2000], [5, 'dm³', 'cm³', 5000], [4, 'L', 'cm³', 4000], [9, 'dm³', 'L', 9]]); return Q(r, t[0] + ' ' + t[1] + ' kaç ' + t[2] + ' eder?', N(t[3]) + ' ' + t[2], [N(t[3] * 10) + ' ' + t[2], N(t[3] / 10) + ' ' + t[2], N(t[3] / 100) + ' ' + t[2]], 'Hacim birimlerinde her basamak 1000 kattır; 1 dm³ = 1 L.'); },
     function (r) { var t = r.pick([[4000, 'cm³', 'dm³', 4], [6000, 'cm³', 'L', 6], [8000, 'dm³', 'm³', 8], [2500, 'cm³', 'dm³', 2.5]]); return Q(r, N(t[0]) + ' ' + t[1] + ' kaç ' + t[2] + ' eder?', N(t[3]) + ' ' + t[2], [N(t[3] * 10) + ' ' + t[2], N(t[3] / 10) + ' ' + t[2], N(t[3] * 100) + ' ' + t[2]], 'Küçük birimden büyüğe: 1000’e bölünür.'); },
     function (r) { var a = r.pick([50, 40, 60]), b = r.pick([40, 30, 20]), c = r.pick([30, 20, 25]); var L = a * b * c / 1000; return Q(r, 'Boyutları ' + a + ' cm × ' + b + ' cm × ' + c + ' cm olan dikdörtgen biçimli bir akvaryuma en fazla kaç litre su konabilir?', N(L), [N(L * 10), N(L / 10), N(a * b * c)], a + '·' + b + '·' + c + ' = ' + N(a * b * c) + ' cm³ = ' + N(L) + ' L'); },
     function (r) { var k = r.pick([2, 3, 4]); return Q(r, 'Bir küpün tüm ayrıtları ' + k + ' katına çıkarılırsa hacmi kaç katına çıkar?', k * k * k, [k * k, k, 6 * k], 'Hacim ' + k + '·' + k + '·' + k + ' = ' + k * k * k + ' katına çıkar.'); }]);

  // ============ HAFTA 9 ============
  wk(12, 9, 'Yüzey Alanı ve Hacim Problemleri', 5,
    ['Dikdörtgenler prizmasının yüzey alanı ve hacmi ile ilgili problemleri çözer.'],
    [['Strateji', '<ol><li>Şekli çizin, ayrıtları yazın.</li><li>Sorulan alan mı hacim mi? Birimleri aynı yapın.</li><li>Formülü seçin; hesaplayın.</li><li>Sonuç mantıklı mı? (Küçük kutu 1000 L olamaz.)</li></ol>'],
     ['Çözümlü Örnekler', EX('<b>Havuz:</b> 4 m × 3 m × 2 m’lik havuz, dakikada 100 litre su veren musluktan kaç dakikada dolar?<br>V = 24 m³ = 24 000 L. 24 000 ÷ 100 = <b>240 dakika</b>.<br><b>Su yüksekliği:</b> Tabanı 20 × 25 cm olan boş kaba 5 L su konuyor. 5 L = 5000 cm³; yükseklik = 5000 ÷ 500 = <b>10 cm</b>.')],
     ['Küpte Alan–Hacim', EX('Yüzey alanı 96 cm² olan küp: 6a² = 96 → a = 4 → V = 4³ = <b>64 cm³</b>.<br>Hacmi 125 cm³ olan küp: a = 5 → S = 6·25 = <b>150 cm²</b>.')],
     ['Etkinlik', ACT('Evdeki bir kutu (ayakkabı kutusu) ölçülerini alın; yüzey alanını ve hacmini hesaplayın. Kaç adet 1 cm’lik küp sığar? Kutuyu gerçekten dolduracak malzeme hesaplayın.')]],
    [function (r) { var a = r.pick([4, 5, 6]), b = r.pick([2, 3, 4]), c = r.pick([2, 3]); var V = a * b * c * 1000, d = r.pick([100, 200, 300]); var tt = V / d; return Q(r, a + ' m × ' + b + ' m × ' + c + ' m boyutlarındaki dikdörtgen biçimli bir havuz dakikada ' + d + ' litre su akıtan musluktan kaç dakikada dolar?', N(tt), [N(tt / 10), N(tt * 10), N(a * b * c)], 'V = ' + a * b * c + ' m³ = ' + N(V) + ' L; ' + N(V) + ' ÷ ' + d + ' = ' + N(tt)); },
     function (r) { var a = r.int(2, 6), b = r.int(2, 5), c = r.int(2, 5), p = r.pick([5, 10, 20]); var s = 2 * (a * b + a * c + b * c); return Q(r, a + ' dm × ' + b + ' dm × ' + c + ' dm boyutlarındaki bir kutunun tamamı boyanacak. 1 dm² boyanması ' + p + ' kuruş ise toplam boya maliyeti kaç kuruştur?', s * p, [a * b * c * p, s, s * p + p], 'Yüzey alanı ' + s + ' dm² → ' + s + ' · ' + p + ' = ' + s * p); },
     function (r) { var a = r.pick([20, 25, 40]), b = r.pick([20, 25, 10]), L = r.pick([2, 4, 5, 8]); var ab = a * b; var h = L * 1000 / ab; return Q(r, 'Tabanı ' + a + ' cm × ' + b + ' cm olan dikdörtgen biçimli boş bir kaba ' + L + ' litre su konuluyor. Suyun yüksekliği kaç cm olur?', N(h), [N(h * 2), N(h / 2), N(L * 10)], L + ' L = ' + N(L * 1000) + ' cm³; yükseklik = ' + N(L * 1000) + ' ÷ ' + ab + ' = ' + N(h)); },
     function (r) { var k = r.pick([2, 3, 4, 5]), a = k * r.int(2, 3), b = k * r.int(2, 3), c = k * r.int(1, 3); return Q(r, 'İç boyutları ' + a + ' cm × ' + b + ' cm × ' + c + ' cm olan bir kutuya kenarı ' + k + ' cm olan eş küplerden en fazla kaç tane sığar?', (a / k) * (b / k) * (c / k), [a * b * c / k, (a / k) * (b / k), (a / k) + (b / k) + (c / k)], 'Her ayrıta ' + a / k + ', ' + b / k + ', ' + c / k + ' küp sığar → çarpım'); },
     function (r) { var a = r.int(2, 9); return Q(r, 'Yüzey alanı ' + 6 * a * a + ' cm² olan bir küpün hacmi kaç cm³’tür?', a * a * a, [6 * a, a * a, 6 * a * a], '6a² = ' + 6 * a * a + ' → a = ' + a + ' → V = ' + a * a * a); },
     function (r) { var a = r.int(2, 9); return Q(r, 'Hacmi ' + a * a * a + ' cm³ olan bir küpün yüzey alanı kaç cm²’dir?', 6 * a * a, [a * a * a, 4 * a * a, 6 * a], 'a = ' + a + ' → S = 6·' + a * a + ' = ' + 6 * a * a); },
     function (r) { var a = r.pick([4, 5, 6]), b = r.pick([3, 4]), h = r.int(2, 5); var V = a * b * h, S = 2 * (a * b + a * h + b * h); return Q(r, 'Taban kenarları ' + a + ' cm ve ' + b + ' cm, hacmi ' + V + ' cm³ olan dikdörtgenler prizmasının yüzey alanı kaç cm²’dir?', S, [V, S / 2, S + 2 * a], 'Yükseklik = ' + V + ' ÷ ' + a * b + ' = ' + h + '; S = 2·(' + a * b + ' + ' + a * h + ' + ' + b * h + ') = ' + S); },
     function (r) { var a = r.pick([20, 30]), b = r.pick([10, 15]), h = r.pick([4, 6]); var V = a * b * h, s = 10; var hh = V / (s * s); return Q(r, a + ' × ' + b + ' × ' + h + ' cm’lik dolu bir kaptaki su, tabanı ' + s + ' × ' + s + ' cm olan boş bir kaba boşaltılırsa suyun yüksekliği kaç cm olur?', N(hh), [N(hh * 2), N(hh / 2), N(h)], 'V = ' + V + ' cm³; yükseklik = ' + V + ' ÷ ' + s * s + ' = ' + N(hh)); }]);
})();
