/* 7. SINIF — 3. İstatistik, 4. Dönüşüm, 5. Geometrik Şekiller, 6. Sayılar ve Nicelikler (2) — Hafta 10-22 */
(function () {
  'use strict';
  var N = MC.num, Q = MC.Q, F = MC.frac, R = window.R7, sh = R.sh, FQ = R.FQ, dec = R.dec, gcd = R.gcd;
  TEMAS.push({ id: 13, n: 3, grade: 7, title: 'İstatistiksel Araştırma Süreci', hours: 25, color: '#0984e3',
    summary: 'Veri türleri, araştırma sorusu, grafikler, çizgi grafiği, ortalama, ortanca, tepe değer, açıklık, ortalama mutlak sapma, hata ve yanlılık.' });
  TEMAS.push({ id: 14, n: 4, grade: 7, title: 'Dönüşüm', hours: 12, color: '#00a8a8',
    summary: 'Yansıma, simetri, noktanın simetriği, orta dikme ve açıortay, pergel-cetvel çizimleri.' });
  TEMAS.push({ id: 15, n: 5, grade: 7, title: 'Geometrik Şekiller: Üçgende Yardımcı Elemanlar', hours: 8, color: '#d63031',
    summary: 'Üçgenin temel elemanları, kenarortay ve açıortay, özellikleri ve inşaları.' });
  TEMAS.push({ id: 16, n: 6, grade: 7, title: 'Sayılar ve Nicelikler (2): Oran, Orantı ve Yüzde', hours: 30, color: '#6c5ce7',
    summary: 'Oran, birim oran, denk oran, orantı, doğru orantı, yüzde, artış-azalış, indirim, kâr-zarar.' });

  function wk(tema, no, title, hours, outcomes, lesson, makers) {
    WEEKS.push({ grade: 7, tema: tema, no: 100 + no, wk: no, title: title, hours: hours, code: '', outcomes: outcomes,
      lesson: lesson.map(function (s) { return { h: s[0], html: s[1] }; }), makers: makers });
  }
  var DEF = function (t) { return '<div class="box def">' + t + '</div>'; };
  var EX = function (t) { return '<div class="box ex">' + t + '</div>'; };
  var TIP = function (t) { return '<div class="box tip">' + t + '</div>'; };
  var WARN = function (t) { return '<div class="box warn">' + t + '</div>'; };
  var ACT = function (t) { return '<div class="box idea"><b>Etkinlik:</b> ' + t + '</div>'; };
  function sum(a) { return a.reduce(function (x, y) { return x + y; }, 0); }
  function sorted(a) { return a.slice().sort(function (x, y) { return x - y; }); }
  function median(a) { var s = sorted(a), n = s.length; return n % 2 ? s[(n - 1) / 2] : (s[n / 2 - 1] + s[n / 2]) / 2; }
  function mode(a) { var c = {}; a.forEach(function (x) { c[x] = (c[x] || 0) + 1; }); var best = -1, bv = null, uniq = true; Object.keys(c).forEach(function (k) { if (c[k] > best) { best = c[k]; bv = +k; uniq = true; } else if (c[k] === best) uniq = false; }); return uniq ? bv : null; }
  function dset(r, n, lo, hi) { for (var t = 0; t < 200; t++) { var a = []; for (var i = 0; i < n; i++) a.push(r.int(lo, hi)); var m = mode(a); if (m !== null && a.filter(function (x) { return x === m; }).length >= 2) return a; } return [lo + 2, lo + 2, lo + 3, lo + 4, lo + 5, lo + 1, lo].slice(0, n); }
  function pctStr(x) { return '%' + N(Math.round(x * 100) / 100); }

  // ============ HAFTA 10 ============
  var KATEG = ['Göz rengi', 'En sevilen ders', 'Doğum yeri', 'Okula geliş şekli', 'Favori film türü'];
  var KESIK = ['Kardeş sayısı', 'Ayakkabı numarası', 'Haftada okunan kitap sayısı', 'Sınıftaki öğrenci sayısı', 'Evdeki oda sayısı'];
  var SUREKLI = ['Boy uzunluğu', 'Vücut ağırlığı', 'Bir koşunun süresi', 'Havanın sıcaklığı', 'Bir su bardağının kapasitesi'];
  wk(13, 10, 'Veri Türleri, Araştırma Sorusu ve Veri Toplama', 5,
    ['Kategorik, nicel kesikli ve nicel sürekli veriyi ayırt eder.', 'İstatistiksel araştırma sorusu oluşturur, veri toplama planı yapar.'],
    [['Ders Açılışı', '<p>“Sınıfın en sevdiği spor ne?”, “Öğrencilerin boyları nasıl dağılıyor?” Bu sorular için sayarak mı, ölçerek mi veri toplarız? Çocuğa sorun ve sınıflandırmasını isteyin.</p>'],
     ['Veri Türleri', '<table class="tbl"><thead><tr><th>Tür</th><th>Özelliği</th><th>Örnek</th></tr></thead><tbody><tr><td>Kategorik</td><td>Gruplara ayrılır</td><td>Göz rengi, favori ders</td></tr><tr><td>Nicel kesikli</td><td>Sayarak bulunur, ara değer almaz</td><td>Kardeş sayısı, ayakkabı numarası</td></tr><tr><td>Nicel sürekli</td><td>Ölçerek bulunur, aralarında sonsuz değer</td><td>Boy, kütle, süre, sıcaklık</td></tr></tbody></table>'],
     ['Araştırma Süreci', '<ol><li><b>Soru:</b> Net, tek anlamlı (betimleme veya karşılaştırma).</li><li><b>Plan:</b> Kimden, nasıl, ne kadar veri? Örneklem tüm grubu temsil etmeli.</li><li><b>Veri topla:</b> Anket, ölçme, gözlem veya hazır veri.</li><li><b>Düzenle:</b> Sıklık tablosu, çetele.</li><li><b>Göster ve özetle, yorumla.</b></li></ol>' + TIP('Yönlendirici sorulardan kaçının; “Herkesin sevdiği X mi, Y mi?” kötü bir sorudur.')],
     ['Etkinlik', ACT('Çocuk ailede bir mini anket yapsın (“hafta içi kaç saat ekran başındasınız?”), çetele tablosu tutup en çok/en az değerleri bulsun.')]],
    [function (r) { var c = r.pick(KATEG); return Q(r, 'Aşağıdakilerden hangisi <b>kategorik</b> veridir?', c, [r.pick(KESIK), r.pick(SUREKLI), 'Bir sınıfın not ortalaması'], 'Kategorik veri gruplara ayrılır.'); },
     function (r) { var c = r.pick(KESIK); return Q(r, 'Aşağıdakilerden hangisi <b>nicel kesikli</b> veridir?', c, [r.pick(KATEG), r.pick(SUREKLI), 'Bir bardaktaki su miktarı'], 'Sayarak bulunur ve ara değer almaz.'); },
     function (r) { var c = r.pick(SUREKLI); return Q(r, 'Aşağıdakilerden hangisi <b>nicel sürekli</b> veridir?', c, [r.pick(KATEG), r.pick(KESIK), 'Sınıftaki sıra sayısı'], 'Ölçerek bulunur ve iki değer arasında sonsuz değer alabilir.'); },
     function (r) { var cs = [['Hangi sınıfta öğrenciler günde daha çok kitap okuyor?', 'Karşılaştırma sorusu'], ['Öğrencilerin en sevdiği ders hangisidir?', 'Betimleme sorusu'], ['Kızlar mı erkekler mi daha çok spor yapıyor?', 'Karşılaştırma sorusu'], ['Sınıfımızın ayakkabı numaraları nasıl dağılıyor?', 'Betimleme sorusu']]; var c = r.pick(cs); return Q(r, '“' + c[0] + '” araştırma sorusu için aşağıdakilerden hangisi doğrudur?', c[1], ['Betimleme sorusu', 'Karşılaştırma sorusu', 'Tahmin sorusu', 'Veri gerektirmeyen soru'].filter(function (x) { return x !== c[1]; }), c[1] + ' türündedir.'); },
     function (r) { return Q(r, 'Okuldaki bütün öğrencilerin en sevdiği ders araştırılırken yalnızca matematik kulübü üyelerine anket uygulanırsa ne olur?', 'Örneklem yanlı olur; sonuç okulu temsil etmez', ['Sonuç kesinlikle doğru olur', 'Veri sürekli hâle gelir', 'Araştırma sorusu karşılaştırmaya dönüşür'], 'Örneklem tüm grubu temsil etmelidir.'); },
     function (r) { var a = r.int(6, 14), b = r.int(4, 10), c = r.int(3, 9), d = r.int(2, 8); var t = a + b + c + d; return Q(r, 'Tabloda ' + t + ' öğrencinin okula geliş şekli verilmiştir. Yürüyerek gelen öğrencilerin tüm öğrencilere oranı (yüzde) kaçtır?<br>' + MC.table(['Geliş şekli', 'Yürüyerek', 'Servis', 'Özel araç', 'Bisiklet'], [['Öğrenci sayısı', a, b, c, d]]), pctStr(a * 100 / t), [pctStr(a * 100 / t + 5), pctStr(b * 100 / t), pctStr(a)], a + '/' + t + ' = ' + pctStr(a * 100 / t)); },
     function (r) { return Q(r, 'Aşağıdaki anket sorularından hangisi <b>yönlendirici</b> olduğu için uygun değildir?', 'Herkesin sevdiği futbolu mu yoksa sıkıcı olan yüzmeyi mi seversin?', ['En sevdiğin spor dalı hangisidir?', 'Haftada kaç saat spor yaparsın?', 'Okula nasıl geliyorsun?'], 'Tarafsız ve yönlendirmeyen soru sorulmalıdır.'); },
     function (r) { var g = r.pick([['boyların (cm)', 'nicel sürekli'], ['kardeş sayılarının', 'nicel kesikli'], ['en sevilen renklerin', 'kategorik']]); return Q(r, 'Bir sınıfta öğrencilerin ' + g[0] + ' incelenecektir. Bu veri hangi türdendir?', g[1], ['kategorik', 'nicel kesikli', 'nicel sürekli'].filter(function (x) { return x !== g[1]; }).concat(['sıralı']), 'Bu veri ' + g[1] + ' türündendir.'); }]);

  // ============ HAFTA 11 ============
  wk(13, 11, 'Verileri Grafiklerle Gösterme ve Çizgi Grafiği', 5,
    ['Verileri uygun grafiklerle gösterir.', 'Çizgi grafiğini okur, yorumlar ve oluşturur.'],
    [['Hangi Grafik Ne Zaman?', '<table class="tbl"><thead><tr><th>Grafik</th><th>Ne için?</th></tr></thead><tbody><tr><td>Sütun grafiği</td><td>Kategorileri karşılaştırmak</td></tr><tr><td>Daire grafiği</td><td>Bütünün parçalarını (yüzde) göstermek</td></tr><tr><td>Çizgi grafiği</td><td><b>Zaman içindeki değişimi</b> göstermek</td></tr><tr><td>Nokta/Kök-yaprak</td><td>Sayısal veri dağılımı</td></tr></tbody></table>'],
     ['Çizgi Grafiği Okuma', '<p>Bir kentte aylık ortalama sıcaklık:</p>' + R.lineChart(['Oca', 'Şub', 'Mar', 'Nis', 'May', 'Haz'], [2, 4, 8, 13, 18, 23], { lo: 0, hi: 24 }) + EX('En yüksek: Haziran (23°C). En çok artış (5°C): Mart → Nisan, Nisan → Mayıs ve Mayıs → Haziran aralıklarında. Genel eğilim: artıyor.')],
     ['Daire Grafiği', DEF('Tam çember 360° = %100. Bir dilimin merkez açısı = yüzde × 3,6.') + EX('90°’lik dilim = %25; %40’lık dilim = 40 · 3,6 = 144°.')],
     ['Etkinlik', ACT('Çocuk bir hafta boyunca her gün sabah sıcaklığını ya da ders çalışma süresini not edip çizgi grafiği çizsin. Hangi gün en çok artış/azalış olmuş?')]],
    [function (r) { var v = []; var b = r.int(5, 20); for (var i = 0; i < 6; i++) v.push(b + r.int(0, 6) + i * r.int(0, 3)); var mx = v.indexOf(Math.max.apply(null, v)); if (new Set(v).size !== 6) v = [8, 12, 15, 19, 17, 22]; mx = v.indexOf(Math.max.apply(null, v)); var L = ['Oca', 'Şub', 'Mar', 'Nis', 'May', 'Haz']; return Q(r, 'Grafiğe göre en yüksek değer hangi ayda görülmüştür?<br>' + R.lineChart(L, v, { lo: 0, hi: Math.max.apply(null, v) + 2 }), L[mx], L.filter(function (x, i) { return i !== mx; }), 'En yüksek nokta ' + L[mx]); },
     function (r) { var v = [r.int(10, 14), r.int(15, 20), r.int(18, 24), r.int(22, 30), r.int(24, 34), r.int(30, 40)]; v = v.map(function (x, i) { return x + i; }); var L = ['1.gün', '2.gün', '3.gün', '4.gün', '5.gün', '6.gün']; var idx = 0, best = -1; for (var i = 1; i < 6; i++) { if (v[i] - v[i - 1] > best) { best = v[i] - v[i - 1]; idx = i; } } var cnt = 0; for (var j = 1; j < 6; j++) if (v[j] - v[j - 1] === best) cnt++; if (cnt > 1) { v[5] += 7; best = v[5] - v[4]; idx = 5; } return Q(r, 'Grafikte en büyük artış hangi iki gün arasında olmuştur?<br>' + R.lineChart(L, v, { lo: 0, hi: Math.max.apply(null, v) + 4 }), L[idx - 1] + ' – ' + L[idx], L.slice(0, 5).map(function (x, i) { return L[i] + ' – ' + L[i + 1]; }).filter(function (x, i) { return i !== idx - 1; }), 'Farklar: ' + v.slice(1).map(function (x, i) { return x - v[i]; }).join(', ')); },
     function (r) { var d = r.pick([[25, 90], [50, 180], [10, 36], [40, 144], [20, 72], [75, 270]]); return Q(r, 'Bir daire grafiğinde %' + d[0] + '’i gösteren dilimin merkez açısı kaç derecedir?', d[1] + '°', [(d[1] + 30) + '°', (d[1] / 2) + '°', d[0] + '°'], '%' + d[0] + ' · 3,6 = ' + d[1] + '°'); },
     function (r) { var a = r.pick([30, 45, 60, 90, 120, 180]); return Q(r, 'Bir daire grafiğinde merkez açısı ' + a + '° olan dilim yüzde kaçı gösterir?', pctStr(a / 3.6), [pctStr(a / 3), pctStr(a / 2), pctStr(a)], a + ' ÷ 3,6 = ' + pctStr(a / 3.6)); },
     function (r) { var cs = [['Bir şehrin 12 ay boyunca aylık yağış miktarının değişimi', 'Çizgi grafiği'], ['Bir sınıfta en sevilen 5 meyvenin karşılaştırılması', 'Sütun grafiği'], ['Aylık bütçede gelirin ev, yemek ve ulaşım payları', 'Daire grafiği']]; var c = r.pick(cs); return Q(r, c[0] + ' için en uygun gösterim hangisidir?', c[1], ['Çizgi grafiği', 'Sütun grafiği', 'Daire grafiği', 'Kök-yaprak gösterimi'].filter(function (x) { return x !== c[1]; }), 'Zamanla değişim → çizgi; karşılaştırma → sütun; bütünün parçaları → daire.'); },
     function (r) { var v = [r.int(6, 12), r.int(10, 18), r.int(14, 22), r.int(12, 20), r.int(8, 16)]; v = v.map(function (x, i) { return x + i * 2; }); var L = ['Pzt', 'Sal', 'Çar', 'Per', 'Cum']; var tot = sum(v); if (tot % 5) { v[4] += 5 - tot % 5; tot = sum(v); } return Q(r, 'Grafikte günlük satılan simit sayıları verilmiştir. Beş günün ortalaması kaçtır?<br>' + R.lineChart(L, v, { lo: 0, hi: Math.max.apply(null, v) + 2 }), tot / 5, [tot / 5 + 1, tot / 5 - 1, tot / 5 + 3], 'Toplam ' + tot + ' ÷ 5 = ' + tot / 5 + ' (değerler: ' + v.join(', ') + ')'); },
     function (r) { var t = r.pick([[1, 40], [2, 60], [3, 75], [4, 85]]); return Q(r, 'Bir çizgi grafiğinde noktalar yukarı doğru gidiyorsa verinin zamanla nasıl değiştiği söylenebilir?', 'Arttığı', ['Azaldığı', 'Hiç değişmediği', 'Önce arttığı sonra sabit kaldığı'], 'Yükselen çizgi artışı gösterir.'); },
     function (r) { var a = r.int(20, 40), b = r.int(10, 30), c = r.int(10, 30); var tot = a + b + c; return Q(r, 'Bir kutuda ' + tot + ' bilye vardır: ' + a + ' kırmızı, ' + b + ' mavi, ' + c + ' yeşil. Bunu daire grafiğiyle gösterirsek kırmızı bilyelerin merkez açısı kaç derece olur?', N(Math.round(a / tot * 360 * 10) / 10) + '°', [N(Math.round(b / tot * 360 * 10) / 10) + '°', N(Math.round(a / tot * 180 * 10) / 10) + '°', N(a) + '°'], a + '/' + tot + ' · 360° = ' + N(Math.round(a / tot * 360 * 10) / 10) + '°'); }]);

  // ============ HAFTA 12 ============
  wk(13, 12, 'Ortalama, Ortanca, Tepe Değer ve Açıklık', 5,
    ['Aritmetik ortalama, ortanca, tepe değer ve açıklığı hesaplar ve yorumlar.'],
    [['Ders Açılışı', '<p>6. sınıfta öğrendiklerimizi hatırlayalım: “Verileri tek bir sayıyla nasıl özetleriz?” Yeni bölüm: ortalama bir tablodan (frekanstan) nasıl hesaplanır? Uç değer varsa hangi özet seçilir?</p>'],
     ['Dört Özet Ölçü', '<ul><li><b>Aritmetik ortalama:</b> toplam ÷ veri sayısı (uç değerlerden etkilenir).</li><li><b>Ortanca:</b> sıralıdaki orta değer (çift sayıda veride ortadaki ikinin ortalaması).</li><li><b>Tepe değer:</b> en çok tekrar eden değer.</li><li><b>Açıklık:</b> en büyük − en küçük.</li></ul>'],
     ['Frekans Tablosundan Ortalama', EX('Not: 2, 3, 4 — Öğrenci sayısı: 3, 4, 3.<br>Toplam = 2·3 + 3·4 + 4·3 = 30; veri sayısı 10 → ortalama <b>3</b>.')],
     ['Hangisi Uygun?', TIP('Uç değer varsa (maaşlar: 1000, 1100, 1200, 1300, 10 000) <b>ortanca</b> daha dengelidir. Kategorik veride merkez için <b>tepe değer</b> kullanılır.')]],
    [function (r) { var n = r.pick([5, 6, 7, 8]), m = r.int(10, 40); var d = []; for (var i = 0; i < n - 1; i++) d.push(r.int(m - 8, m + 8)); var last = m * n - sum(d); if (last < 1) { last = m; d[0] += m * n - sum(d) - last; } d.push(last); return Q(r, d.join(', ') + ' veri grubunun aritmetik ortalaması kaçtır?', m, [m + 1, m - 1, m + 2], 'Toplam ' + m * n + ' ÷ ' + n + ' = ' + m); },
     function (r) { var n = r.pick([5, 7, 9]); var d = []; for (var i = 0; i < n; i++) d.push(r.int(3, 50)); var md = median(d); var s = sorted(d); return Q(r, d.join(', ') + ' veri grubunun ortancası kaçtır?', md, [s[0], s[n - 1], Math.round(sum(d) / n) === md ? md + 2 : Math.round(sum(d) / n)], 'Sıralı: ' + s.join(', ') + ' → ortadaki ' + md); },
     function (r) { var n = r.pick([6, 8]); var d = []; for (var i = 0; i < n; i++) d.push(r.int(3, 40)); var s = sorted(d), md = median(d); return Q(r, d.join(', ') + ' veri grubunun ortancası kaçtır?', N(md), [N(s[n / 2]), N(s[n / 2 - 1]), N(md + 1)], 'Sıralı: ' + s.join(', ') + '; ortadaki ikisinin ortalaması ' + N(md)); },
     function (r) { var d = dset(r, r.int(9, 12), 1, 9); var m = mode(d); return Q(r, d.join(', ') + ' veri grubunun tepe değeri kaçtır?', m, [m + 1, m - 1 > 0 ? m - 1 : m + 2, m + 2], 'En çok tekrar eden değer ' + m); },
     function (r) { var n = r.int(6, 9); var d = []; for (var i = 0; i < n; i++) d.push(r.int(4, 60)); var s = sorted(d); return Q(r, d.join(', ') + ' veri grubunun açıklığı kaçtır?', s[n - 1] - s[0], [s[n - 1], s[n - 1] - s[0] + 2, s[n - 1] + s[0]], s[n - 1] + ' − ' + s[0] + ' = ' + (s[n - 1] - s[0])); },
     function (r) { var vs = [2, 3, 4], fr = [r.int(2, 5), r.int(2, 5), r.int(2, 5)]; var tot = sum(fr), s = 2 * fr[0] + 3 * fr[1] + 4 * fr[2]; var m = s / tot; return Q(r, 'Tabloda bir sınavdaki notlar ve öğrenci sayıları verilmiştir. Sınıfın not ortalaması kaçtır?<br>' + MC.table(['Not', '2', '3', '4'], [['Öğrenci sayısı'].concat(fr)]), N(Math.round(m * 100) / 100), [N(Math.round((m + 0.5) * 100) / 100), N(3), N(Math.round((m - 0.4) * 100) / 100)], 'Toplam = ' + s + ', öğrenci = ' + tot + ' → ' + N(Math.round(m * 100) / 100)); },
     function (r) { var m = r.int(70, 85), n = r.pick([4, 5]), inc = r.pick([1, 2, 3]); var need = (m + inc) * (n + 1) - m * n; return Q(r, n + ' sınavın ortalaması ' + m + ' iken bir sınav daha girilerek ortalamanın ' + inc + ' puan artması isteniyor. Bu son sınavdan kaç alınmalıdır?', need, [need - 5, need + 5, m + inc], (m + inc) + '·' + (n + 1) + ' − ' + m + '·' + n + ' = ' + need); },
     function (r) { var b = r.int(1000, 1400); return Q(r, 'Bir ofiste 5 çalışanın maaşları ' + N(b) + ', ' + N(b + 100) + ', ' + N(b + 200) + ', ' + N(b + 300) + ' ve ' + N(b * 8) + ' TL’dir. Tipik maaşı anlatmak için hangi ölçü daha uygundur?', 'Ortanca; çünkü uç değerden etkilenmez', ['Aritmetik ortalama; çünkü uç değerleri de içerir', 'Açıklık; çünkü merkezi gösterir', 'Tepe değer; çünkü her zaman vardır'], 'Uç değer ortalamayı büyütür; ortanca dengelidir.'); }]);

  // ============ HAFTA 13 ============
  function madOf(d) { var m = sum(d) / d.length, s = 0; d.forEach(function (x) { s += Math.abs(x - m); }); return [m, s / d.length]; }
  wk(13, 13, 'Ortalama Mutlak Sapma ve Dağılımları Karşılaştırma', 5,
    ['Ortalama mutlak sapmayı hesaplar ve yorumlar.', 'Veri dağılımlarını merkez ve yayılım ölçüleriyle karşılaştırır.'],
    [['Ders Açılışı', '<p>İki basketbolcunun ortalaması 20 sayı. Biri hep 18–22 atıyor, diğeri bir maç 5 bir maç 35. Aynı ortalama ama aynı oyuncu mu? Bu farkı sayıyla anlatmak için <b>yayılım</b> ölçüsüne ihtiyacımız var.</p>'],
     ['Ortalama Mutlak Sapma', DEF('Her verinin ortalamadan uzaklığının (mutlak sapma) ortalamasıdır.<br><b>Adımlar:</b> 1) Ortalamayı bul. 2) Her veriden ortalamayı çıkar, mutlak değer al. 3) Bu uzaklıkların ortalamasını bul.') + EX('Veri: 4, 6, 8, 10, 12 → ortalama 8. Sapmalar: 4, 2, 0, 2, 4 → toplam 12 → OMS = 12 ÷ 5 = <b>2,4</b>.') + TIP('OMS küçükse veriler ortalamaya <b>yakın</b> (homojen), büyükse <b>dağınık</b>dır.')],
     ['Dağılımları Karşılaştırma', EX('A: 18, 20, 22 (ort. 20, OMS ≈ 1,33)<br>B: 5, 20, 35 (ort. 20, OMS = 10)<br>İkisinin ortalaması aynı; A daha tutarlı.')],
     ['Etkinlik', ACT('Çocuk iki farklı günde 5’er kez zar atsın, sonuçların ortalama mutlak sapmasını bulsun; hangi günün sonuçları daha dağınık?')]],
    [function (r) { var m = r.int(8, 20); var a = r.int(1, 4), b = r.int(1, 4); var d = [m - a - b, m - a, m, m + a, m + a + b]; var mo = madOf(d); return Q(r, d.join(', ') + ' veri grubunun ortalama mutlak sapması kaçtır?', N(Math.round(mo[1] * 100) / 100), [N(Math.round(mo[1] * 100) / 100 + 1), N(Math.round(mo[1] * 100) / 100 + 0.4), N(mo[0])], 'Ortalama ' + mo[0] + '; sapmalar ' + d.map(function (x) { return Math.abs(x - mo[0]); }).join(', ') + ' → OMS ' + N(Math.round(mo[1] * 100) / 100)); },
     function (r) { var m = r.int(10, 30); var A = [m - 2, m, m + 2], B = [m - 10, m, m + 10]; var which = r.pick(['A', 'B']); var sA = madOf(A)[1], sB = madOf(B)[1]; return Q(r, 'İki sınıfın puanları: A sınıfı ' + A.join(', ') + '; B sınıfı ' + B.join(', ') + '. Hangi sınıfın puanları daha az dağılmıştır (ortalamadan daha yakındır)?', 'A sınıfı', ['B sınıfı', 'İkisi de aynı', 'Belirlenemez'], 'İki sınıfın da ortalaması ' + m + '; A’nın OMS’si ' + N(Math.round(sA * 100) / 100) + ' ve B’nin ' + N(Math.round(sB * 100) / 100) + '.'); },
     function (r) { var m = r.int(5, 20); var d = [m - 2, m - 2, m + 2, m + 2]; return Q(r, d.join(', ') + ' veri grubunun ortalama mutlak sapması kaçtır?', 2, [1, 4, m], 'Ortalama ' + m + '; her veri 2 uzakta → OMS = 2'); },
     function (r) { return Q(r, 'Ortalama mutlak sapma hakkında aşağıdakilerden hangisi doğrudur?', 'Küçük olması verilerin ortalamaya yakın olduğunu gösterir', ['Küçük olması verilerin çok dağınık olduğunu gösterir', 'Negatif değer alabilir', 'Her zaman ortalamaya eşittir'], 'OMS, ortalamadan ortalama uzaklıktır; küçükse veri homojendir.'); },
     function (r) { var d = [r.int(5, 8), r.int(9, 12), r.int(13, 16), r.int(17, 20)]; var s = sum(d); if (s % 4) d[3] += 4 - s % 4; var mo = madOf(d); return Q(r, d.join(', ') + ' verilerinin aritmetik ortalaması kaçtır?', mo[0], [mo[0] + 1, mo[0] - 1, mo[0] + 2], 'Toplam ÷ 4 = ' + mo[0]); },
     function (r) { var m = r.int(15, 30); return Q(r, 'Aynı ortalamaya sahip iki veri grubundan birinin açıklığı 4, diğerinin açıklığı 30’dur. Hangi grup daha dağınıktır?', 'Açıklığı 30 olan', ['Açıklığı 4 olan', 'İkisi de eşit dağınıktır', 'Söylenemez'], 'Açıklık büyükse veriler daha geniş aralığa yayılmıştır.'); },
     function (r) { var m = r.int(10, 40); var d = [m - 6, m - 2, m + 2, m + 6]; var mo = madOf(d); return Q(r, d.join(', ') + ' verileri için ortalama ve ortalama mutlak sapma sırasıyla kaçtır?', m + ' ve 4', [m + ' ve 2', (m + 2) + ' ve 4', m + ' ve 6'], 'Ortalama ' + m + '; sapmalar 6, 2, 2, 6 → 16 ÷ 4 = 4'); },
     function (r) { var d = [4, 6, 8, 10, 12]; return Q(r, '4, 6, 8, 10 ve 12 verilerinde ortalama mutlak sapma kaçtır?', '2,4', ['2', '3', '2,5'], 'Ortalama 8; sapmalar 4,2,0,2,4 → 12 ÷ 5 = 2,4'); }]);

  // ============ HAFTA 14 ============
  wk(13, 14, 'Grafik ve Raporlardaki Hata, Yanlılık ve Veriye Dayalı Karar', 5,
    ['Grafik ve raporlardaki hata veya yanlılıkları belirler.', 'Veriye dayalı karar verir.'],
    [['Dedektif Gibi Oku', '<ol><li>Veri kimden toplanmış? Örneklem yeterli ve temsilci mi?</li><li>Grafik dürüst mü? Eksen 0’dan başlıyor mu, aralıklar eşit mi?</li><li>Özet doğru yorumlanmış mı? (Ortalama = herkes değildir.)</li><li>Neden–sonuç iddiası var mı? (İlişki = neden değil.)</li><li>Zaman aralığı seçilerek veri “süslenmiş” mi?</li></ol>'],
     ['Yanıltıcı Grafik', '<div class="twocol"><div>' + MC.barChart(['A', 'B'], [52, 54], { base: 50, top: 55, steps: 5 }) + '<p class="note">Eksen 50’den başlıyor → B, A’nın 3 katı gibi görünüyor.</p></div><div>' + MC.barChart(['A', 'B'], [52, 54], { base: 0, top: 60, steps: 6 }) + '<p class="note">Eksen 0’dan başlıyor → fark küçük.</p></div></div>'],
     ['Veriye Dayalı Karar', EX('Okul gezisi için 3 yer seçeneği; ankete 120 öğrenci katıldı: A 30, B 54, C 36. En çok tercih eden B’dir (%45) → B seçilebilir. Ancak örneklem yalnızca 6. sınıflardansa karar tüm okulu temsil etmez.')],
     ['Etkinlik', ACT('Gazete ya da internetten bir grafik bulun; yanıltıcı yönü var mı? Doğru çizimini yapın.')]],
    [function (r) { var a = r.int(50, 70), d = r.int(1, 4); return Q(r, 'Bir mağaza, çubuk grafiği 50’den başlatarak A şubesinin satışını ' + a + ', B şubesinin satışını ' + (a + d) + ' gösteriyor ve “B’nin satışları kat kat fazla!” diyor. Grafikteki hata nedir?', 'Dikey eksen 0’dan başlamadığı için fark olduğundan büyük görünüyor', ['Grafik çubuklu olmamalıdır', 'A şubesinin değeri yanlış yazılmıştır', 'Grafikte renk yoktur'], 'Eksen 0’dan başlamazsa küçük fark büyük görünür.'); },
     function (r) { var s = r.int(8, 12); return Q(r, 'Bir marka, ürününü yalnızca mağazadan çıkan ' + s + ' kişiye sorarak “öğrencilerin çoğu seviyor” diyor. Bu çıkarım için ne söylenir?', 'Örneklem küçük ve yanlıdır; genellenemez', ['Kesinlikle doğrudur', 'Soruyu yeniden yazmak yeterlidir', 'Veri yoktur'], 'Seçilen kişiler tüm öğrencileri temsil etmiyor.'); },
     function (r) { return Q(r, 'Yaz aylarında hem dondurma satışı hem de yüzme kazaları artıyor. “Dondurma yemek yüzme kazalarına neden oluyor” yorumu için ne söylenir?', 'Hatalıdır; sıcak hava her ikisini de artırmış olabilir', ['Doğrudur', 'Verinin kesin sonucudur', 'Kazalar yanlış sayılmıştır'], 'İki şey birlikte değişse bile biri diğerinin nedeni olmayabilir.'); },
     function (r) { var m = r.int(60, 85); return Q(r, 'Sınıfın sınav ortalaması ' + m + ' çıkmıştır. Aşağıdaki yorumlardan hangisi <b>hatalıdır</b>?', 'Herkes tam olarak ' + m + ' almıştır', ['Bazıları ' + m + '’den fazla, bazıları az almış olabilir', 'Toplam puan öğrenci sayısına bölünerek bulunmuştur', 'En yüksek puan ' + m + '’den küçük değildir'], 'Ortalama herkesin aynı puanı aldığı anlamına gelmez.'); },
     function (r) { var a = r.int(14, 20), b = r.int(8, 13), c = r.int(4, 8); return Q(r, 'Tabloda ' + (a + b + c) + ' öğrencinin tercih ettiği kulüpler verilmiştir. Hangi yorum veriye uygundur?<br>' + MC.table(['Kulüp', 'Satranç', 'Resim', 'Müzik'], [['Öğrenci', a, b, c]]), 'Satranç en çok tercih edilmiştir', ['Resim en çok tercih edilmiştir', 'Müzik, satrançtan çok tercih edilmiştir', 'Hepsi eşit tercih edilmiştir'], 'Satranç ' + a + ' ile en yüksektir.'); },
     function (r) { return Q(r, 'Bir kişi sadece 3 arkadaşına sorup “bütün okulun %80’i yaz tatilini seviyor” demiştir. Eksiklik nedir?', 'Çok az kişiye sorularak okula genelleme yapılmıştır', ['Soru yanlış yazılmıştır', 'Yüzde hesaplanamaz', 'Veri kategorik değildir'], 'Küçük örneklemden genelleme yapılamaz.'); },
     function (r) { var m = r.int(1000, 1400); return Q(r, 'Bir şirket “maaş ortalamamız ' + N(m * 3) + ' TL” diyor; çalışanların çoğunun maaşı ' + N(m) + ' TL civarı ve yönetimin maaşı çok yüksek. En uygun yorum hangisidir?', 'Uç değerler ortalamayı yükseltmiştir; ortanca daha doğru fikir verir', ['Ortalama her zaman doğrudur', 'Açıklık maaşları gösterir', 'Tepe değer bulunamaz'], 'Uç değerler ortalamayı yanıltıcı kılabilir.'); },
     function (r) { var a = r.int(20, 40), b = r.int(40, 60), c = r.int(20, 40); var t = a + b + c; return Q(r, 'Okul gezisi için ' + t + ' öğrencinin oyu: A yeri ' + a + ', B yeri ' + b + ', C yeri ' + c + '. Veriye dayalı karara göre hangi yer seçilmelidir?', 'B yeri', ['A yeri', 'C yeri', 'Hiçbiri seçilemez'], 'En çok oy alan yer ' + (b >= a && b >= c ? 'B (' + b + ')' : 'B') + '.'); }]);

  // ============ HAFTA 15 ============
  wk(14, 15, 'Yansıma Dönüşümü ve Simetri', 6,
    ['Bir şeklin yansıma altındaki görüntüsünü çizer.', 'Bir noktanın bir doğruya göre simetriğini bulur.'],
    [['Ders Açılışı', '<p>Aynaya bir el koyun: ayna yansımasında el nerede? Kâğıdı katlayıp mürekkep damlatın; açınca simetrik iz oluşur. Bu, <b>yansıma dönüşümü</b>dür.</p>'],
     ['Yansıma', DEF('Bir şeklin bir <b>yansıma doğrusuna</b> göre görüntüsü, her noktanın doğruya olan uzaklığı değişmeden doğrunun diğer tarafına taşınmasıyla bulunur. Nokta ile görüntüsünü birleştiren doğru parçası yansıma doğrusuna <b>diktir</b> ve doğru onun orta noktasından geçer.') + TIP('Yansımada <b>uzunluk ve açı ölçüsü korunur</b>; ama şeklin yönü (sol-sağ) ters döner.')],
     ['Koordinat Düzleminde', DEF('A(x, y) noktasının:<br>• <b>x eksenine</b> göre simetriği: (x, −y)<br>• <b>y eksenine</b> göre simetriği: (−x, y)<br>• <b>x = k doğrusuna</b> göre simetriği: (2k − x, y)<br>• <b>y = k doğrusuna</b> göre simetriği: (x, 2k − y)') + EX('A(3, 2): x eksenine göre (3, −2); y eksenine göre (−3, 2); x = 5 doğrusuna göre (2·5 − 3, 2) = (7, 2).')],
     ['Simetri Ekseni', '<ul><li>Kare: 4, dikdörtgen: 2, eşkenar dörtgen: 2, eşkenar üçgen: 3, ikizkenar üçgen: 1, düzgün altıgen: 6 simetri ekseni vardır.</li></ul>' + ACT('Çocuk kareli kâğıtta bir şekil çizsin, bir doğruya göre yansımasını çizsin; sonra kâğıdı doğru boyunca katlayarak çakışıp çakışmadığını denesin.')]],
    [function (r) { var x = r.int(1, 9), y = r.int(1, 9); return Q(r, 'A(' + x + ', ' + y + ') noktasının x eksenine göre simetriği hangisidir?', '(' + x + ', −' + y + ')', ['(−' + x + ', ' + y + ')', '(−' + x + ', −' + y + ')', '(' + y + ', ' + x + ')'], 'x eksenine göre y işareti değişir.'); },
     function (r) { var x = r.int(1, 9), y = r.int(1, 9); return Q(r, 'B(−' + x + ', ' + y + ') noktasının y eksenine göre simetriği hangisidir?', '(' + x + ', ' + y + ')', ['(−' + x + ', −' + y + ')', '(' + x + ', −' + y + ')', '(' + y + ', −' + x + ')', '(' + (x + 1) + ', ' + y + ')', '(−' + y + ', ' + x + ')'], 'y eksenine göre x işareti değişir.'); },
     function (r) { var x = r.int(1, 6), k = r.int(x + 1, 9), y = r.int(1, 8); return Q(r, 'A(' + x + ', ' + y + ') noktasının x = ' + k + ' doğrusuna göre simetriği hangisidir?', '(' + (2 * k - x) + ', ' + y + ')', ['(' + (k - x) + ', ' + y + ')', '(' + (2 * k + x) + ', ' + y + ')', '(' + x + ', ' + (2 * k - y) + ')', '(' + (2 * k - x + 1) + ', ' + y + ')', '(' + (2 * k - x - 1) + ', ' + y + ')'], '2·' + k + ' − ' + x + ' = ' + (2 * k - x)); },
     function (r) { var x = r.int(1, 8), y = r.int(1, 6), k = r.int(y + 1, 9); return Q(r, 'C(' + x + ', ' + y + ') noktasının y = ' + k + ' doğrusuna göre simetriği hangisidir?', '(' + x + ', ' + (2 * k - y) + ')', ['(' + x + ', ' + (k - y) + ')', '(' + (2 * k - x) + ', ' + y + ')', '(' + x + ', −' + y + ')', '(' + x + ', ' + (2 * k - y + 1) + ')', '(' + x + ', ' + (2 * k - y - 1) + ')'], '2·' + k + ' − ' + y + ' = ' + (2 * k - y)); },
     function (r) { var a = r.int(1, 8), k = r.int(1, 8); var b = 2 * k - a; if (b === a) { b = a + 2; k = a + 1; } var y = r.int(1, 8); return Q(r, 'A(' + a + ', ' + y + ') noktası ile A′(' + b + ', ' + y + ') noktası bir doğruya göre simetriktir. Bu doğrunun denklemi aşağıdakilerden hangisidir?', 'x = ' + (a + b) / 2, ['x = ' + (a + b), 'y = ' + y, 'x = ' + (a + b) / 2 + 1], 'Doğru, iki noktanın tam ortasından geçer: x = (' + a + ' + ' + b + ') ÷ 2'); },
     function (r) { return Q(r, 'Bir şeklin yansıma dönüşümü altındaki görüntüsünde aşağıdakilerden hangisi <b>değişmez</b>?', 'Doğru parçalarının uzunluğu', ['Şeklin konumu', 'Şeklin yönü (sol-sağ)', 'Köşelerin koordinatları'], 'Yansımada uzunluk ve açı ölçüsü korunur.'); },
     function (r) { var f = r.pick([['Kare', 4], ['Dikdörtgen (kare değil)', 2], ['Eşkenar üçgen', 3], ['Eşkenar dörtgen (kare değil)', 2], ['İkizkenar (eşkenar olmayan) üçgen', 1], ['Düzgün altıgen', 6]]); return Q(r, f[0] + ' için simetri ekseni sayısı kaçtır?', f[1], [1, 2, 3, 4, 5, 6].filter(function (x) { return x !== f[1]; }), 'Bu şeklin ' + f[1] + ' simetri ekseni vardır.'); },
     function (r) { var d = r.int(2, 9); return Q(r, 'Bir nokta yansıma doğrusuna ' + d + ' birim uzaklıktadır. Görüntü noktası bu doğruya kaç birim uzaklıktadır?', d, [d * 2, d + 1, d - 1 || 3], 'Yansımada uzaklık korunur; nokta ile görüntüsü doğruya eşit uzaklıktadır.'); }]);

  // ============ HAFTA 16 ============
  wk(14, 16, 'Orta Dikme ve Açıortay ile Pergel–Cetvel İnşaları', 6,
    ['Orta dikme ve açıortay özelliklerini kullanır.', 'Pergel ve ölçüsüz cetvelle orta dikme ve açıortay çizer.'],
    [['Ders Açılışı', '<p>Bir doğru parçasının tam ortasını cetvelsiz nasıl buluruz? Kâğıdı katlayarak iki ucu üst üste getirin; katlama izi orta dikmedir.</p>'],
     ['Orta Dikme', DEF('Bir doğru parçasının orta noktasından geçen ve ona <b>dik</b> olan doğruya <b>orta dikme</b> denir. Orta dikme üzerindeki her nokta doğru parçasının <b>iki ucuna eşit uzaklıktadır</b>.') + EX('[AB] = 10 cm, orta dikme AB’yi D’de kesiyorsa AD = DB = 5 cm. P orta dikme üzerinde ve PA = 12 ise PB = 12 cm.')],
     ['Orta Dikme İnşası', '<ol><li>Pergeli AB’nin yarısından <b>fazla</b> açın.</li><li>A merkezli, ardından B merkezli (aynı açıklıkla) yaylar çizerek iki noktada kesiştirin.</li><li>Kesişim noktalarını ölçüsüz cetvelle birleştirin: orta dikme.</li></ol>'],
     ['Açıortay', DEF('Bir açıyı iki eş açıya ayıran ışına <b>açıortay</b> denir. Açıortay üzerindeki her nokta açının <b>kollarına eşit uzaklıktadır</b>.') + EX('50°’lik açının açıortayı onu 25° ve 25°’ye böler.') + '<p><b>Açıortay inşası:</b> 1) Köşe merkezli yay, kolları keser. 2) Bu iki noktadan aynı açıklıkla yaylar çizilir. 3) Kesişim noktası köşeyle birleştirilir.</p>' + ACT('Kâğıt katlama ile açıortay ve orta dikme bulun; sonra pergelle aynısını yapıp karşılaştırın.')]],
    [function (r) { var a = r.int(3, 15) * 2; return Q(r, '[AB] = ' + a + ' cm. [AB]’nin orta dikmesi AB’yi D noktasında kesiyorsa AD kaç cm’dir?', a / 2, [a, a / 2 + 1, 2 * a], 'Orta dikme orta noktadan geçer: ' + a + ' ÷ 2'); },
     function (r) { var a = r.int(5, 20); return Q(r, 'P noktası [AB]’nin orta dikmesi üzerindedir. PA = ' + a + ' cm ise PB kaç cm’dir?', a, [a * 2, a / 2 + 1, a + 2], 'Orta dikme üzerindeki nokta uçlara eşit uzaklıktadır.'); },
     function (r) { var a = r.int(3, 17) * 10 + 0; if (a > 170) a = 120; return Q(r, 'Ölçüsü ' + a + '° olan bir açının açıortayı açıyı kaç dereceye böler?', (a / 2) + '° ve ' + (a / 2) + '°', [a + '° ve ' + (a / 2) + '°', Math.round(a / 3) + '° ve ' + Math.round(2 * a / 3) + '°', (a / 2) + '° ve ' + a + '°'], 'Açıortay açıyı iki eş açıya ayırır.'); },
     function (r) { var d = r.int(3, 15); return Q(r, 'Bir açının açıortayı üzerindeki P noktasının açının bir koluna uzaklığı ' + d + ' cm ise diğer koluna uzaklığı kaç cm’dir?', d, [d * 2, d + 1, d / 2 + 1], 'Açıortay üzerindeki nokta kollara eşit uzaklıktadır.'); },
     function (r) { return Q(r, 'Orta dikme inşasında pergel açıklığı için hangisi doğrudur?', 'Doğru parçasının yarısından fazla olmalıdır', ['Doğru parçasının yarısından az olmalıdır', 'Tam olarak 1 cm olmalıdır', 'Hiç önemli değildir'], 'Aksi hâlde yaylar kesişmez.'); },
     function (r) { return Q(r, 'Pergel ve ölçüsüz cetvelle yapılan çizimlerde ölçüsüz cetvelin görevi nedir?', 'Doğru çizmek (ölçü almak için kullanılmaz)', ['Uzunluk ölçmek', 'Açı ölçmek', 'Yay çizmek'], 'Ölçüsüz cetvelde cetvel işareti yoktur; yalnızca doğru çizilir.'); },
     function (r) { var a = r.int(2, 8) * 10; return Q(r, 'Bir karenin köşegeni köşe açısını iki eş açıya böler. Bu açılardan her biri kaç derecedir?', '45°', ['30°', '60°', '90°'], 'Kare köşesi 90°; köşegen açıortaydır → 45°.'); },
     function (r) { var a = r.int(3, 9) * 2; return Q(r, 'Bir doğru parçasının orta dikmesi ile doğru parçası arasındaki açı kaç derecedir?', '90°', ['45°', '60°', '180°'], 'Orta dikme doğru parçasına diktir.'); }]);

  // ============ HAFTA 17 ============
  wk(15, 17, 'Üçgende Kenarortay ve Açıortay', 8,
    ['Üçgenin temel elemanlarını tanır.', 'Kenarortay ve açıortay özelliklerini kullanır, pergel-cetvelle çizer.'],
    [['Ders Açılışı', '<p>Karton üçgen kesip köşelerinden karşı kenarların orta noktalarını birleştirin. Üçgeni kalemin ucunda dengeleyebileceğiniz nokta var mı? O nokta <b>ağırlık merkezi</b>dir.</p>'],
     ['Kenarortay', DEF('Üçgenin bir köşesini karşı kenarın <b>orta noktasına</b> birleştiren doğru parçasına <b>kenarortay</b> denir. Üçgenin 3 kenarortayı vardır ve <b>aynı noktada</b> (ağırlık merkezi G) kesişir.') + TIP('Ağırlık merkezi kenarortayı köşeden başlayarak <b>2 : 1</b> oranında böler: AG = 2·GD.') + EX('AD = 18 cm kenarortay ise AG = 12 cm, GD = 6 cm.<br>Dik üçgende <b>hipotenüse ait kenarortay</b> hipotenüsün yarısına eşittir: hipotenüs 10 → kenarortay 5.')],
     ['Açıortay', DEF('Üçgenin bir açısını iki eş açıya bölen doğru parçasına <b>açıortay</b> denir. Üç açıortay da aynı noktada kesişir; bu nokta üçgenin <b>iç teğet çemberinin merkezidir</b> (üç kenara eşit uzaklıkta).') + EX('A açısı 70° ise açıortay onu 35° ve 35°’ye böler.') + TIP('İkizkenar üçgende tepeden inilen doğru parçası aynı zamanda <b>kenarortay, açıortay ve yüksekliktir</b>.')],
     ['İnşa', '<p><b>Kenarortay inşası:</b> Kenarın orta dikmesini çizerek orta noktayı bulun, köşeyle birleştirin. <b>Açıortay inşası:</b> açının açıortayını pergelle çizin.</p>' + ACT('Karton üçgenin ağırlık merkezini bulup kalem ucunda dengeleyin.')]],
    [function (r) { var a = r.int(3, 15) * 2; return Q(r, 'ABC üçgeninde [AD], BC kenarına ait kenarortaydır. BC = ' + a + ' cm ise BD kaç cm’dir?', a / 2, [a, a / 2 + 1, 2 * a], 'Kenarortay kenarı iki eşit parçaya böler.'); },
     function (r) { var u = r.int(2, 8); return Q(r, 'ABC üçgeninde G ağırlık merkezidir ve AD kenarortaydır. AD = ' + 3 * u + ' cm ise AG kaç cm’dir?', 2 * u, [u, 3 * u, 2 * u + 1], 'AG = 2/3·AD = ' + 2 * u); },
     function (r) { var u = r.int(2, 9); return Q(r, 'G ağırlık merkezi iken GD = ' + u + ' cm ise kenarortayın tamamı AD kaç cm’dir?', 3 * u, [2 * u, u * 4, u + 2], 'AG = 2·GD = ' + 2 * u + '; AD = AG + GD = ' + 3 * u); },
     function (r) { var h = r.int(3, 10) * 2; return Q(r, 'Dik üçgende hipotenüs ' + h + ' cm ise hipotenüse ait kenarortay kaç cm’dir?', h / 2, [h, h / 2 + 1, 2 * h], 'Hipotenüse ait kenarortay hipotenüsün yarısıdır.'); },
     function (r) { var a = r.int(3, 17) * 10; if (a > 170) a = 100; return Q(r, 'ABC üçgeninde A açısı ' + a + '° ve [AD] açıortay ise BAD açısı kaç derecedir?', N(a / 2) + '°', [a + '°', N(a / 3) + '°', N(a * 2) + '°'], 'Açıortay açıyı ikiye böler: ' + a + ' ÷ 2'); },
     function (r) { return Q(r, 'Aşağıdakilerden hangisi <b>yanlıştır</b>?', 'Bir üçgenin kenarortayları farklı noktalarda kesişir', ['Üçgenin üç kenarortayı aynı noktada kesişir', 'Ağırlık merkezi kenarortayı 2 : 1 oranında böler', 'Kenarortay karşı kenarın orta noktasından geçer'], 'Kenarortaylar tek bir noktada (ağırlık merkezi) kesişir.'); },
     function (r) { var a = r.int(3, 9) * 2; return Q(r, 'İkizkenar bir üçgende tabana ait kenarortay ' + 'hangi özelliğe de sahiptir?', 'Aynı zamanda açıortay ve yüksekliktir', ['Yalnızca yüksekliktir', 'Yalnızca açıortaydır', 'Hiçbir özelliği yoktur'], 'İkizkenar üçgenin tepesinden tabana inilen doğru parçası üç görevi de görür.'); },
     function (r) { return Q(r, 'Üçgenin üç açıortayının kesiştiği nokta aşağıdakilerden hangisinin merkezidir?', 'İç teğet çemberin', ['Çevrel çemberin', 'Ağırlık merkezinin', 'Yüksekliklerin'], 'Açıortaylar iç teğet çemberin merkezinde kesişir; bu nokta üç kenara eşit uzaklıktadır.'); }]);

  // ============ HAFTA 18 ============
  wk(16, 18, 'Oran ve Denk Oranlar', 5,
    ['İki nicelik arasındaki oranı belirler ve yorumlar.', 'Temel oran, birim oran, birimli ve birimsiz oranı ayırt eder; denk oranları bulur.'],
    [['Ders Açılışı', '<p>Bir çocuk ile arkadaşları sınıfta kız ve erkek sayılarını karşılaştırsın: 12 kız, 18 erkek. “Kızlar erkeklerin kaçta kaçı?” sorusunu tartışın.</p>'],
     ['Oran Nedir?', DEF('İki niceliğin çarpma ve bölme ile karşılaştırılmasına <b>oran</b> denir. a : b ya da ' + F('a', 'b') + ' (b ≠ 0).') + EX('12 kız, 18 erkek → kız : erkek = 12 : 18 = <b>2 : 3</b> (sadeleştirildi).<br>Kız sayısı / tüm öğrenci = 12/30 = <b>2/5</b>.')],
     ['Oran Türleri', '<ul><li><b>Birimsiz oran:</b> Aynı cins niceliklerin oranı (5 cm / 10 cm = 1/2).</li><li><b>Birimli oran:</b> Farklı cins niceliklerin oranı (120 km / 2 saat = 60 km/saat).</li><li><b>Birim oran:</b> Paydası 1 olan oran: 60 km/saat, 25 TL/kg.</li></ul>'],
     ['Denk Oranlar', DEF('Pay ve paydası aynı sayıyla çarpılan/bölünen oranlar <b>denk orandır</b>: 3 : 5 = 6 : 10 = 12 : 20.') + EX('3 : 5 = ? : 20 → paydayı 4 ile çarptık, payı da: 12.') + ACT('Bir tarif: 2 bardak un, 1 bardak şeker (2 : 1). 4 bardak un için kaç bardak şeker gerekir? Mutfakta deneyin.')]],
    [function (r) { var g = r.int(2, 6), a = r.int(1, 5), b = r.int(a + 1, 7); if (gcd(a, b) !== 1) { a = 2; b = 3; } return Q(r, a * g + ' kız ile ' + b * g + ' erkek öğrencisi olan bir sınıfta kızların erkeklere oranı en sade biçimde hangisidir?', a + ' : ' + b, [b + ' : ' + a, a + ' : ' + (a + b), (a * g) + ' : ' + (b * g)], N(a * g) + ' : ' + N(b * g) + ' = ' + a + ' : ' + b); },
     function (r) { var v = r.pick([60, 40, 80, 50]), t = r.int(2, 5); return Q(r, 'Bir araç ' + t + ' saatte ' + v * t + ' km yol gidiyor. Birim oran (km/saat) kaçtır?', v + ' km/saat', [(v * t) + ' km/saat', (v + t) + ' km/saat', t + ' km/saat'], N(v * t) + ' ÷ ' + t + ' = ' + v); },
     function (r) { var a = r.int(2, 7), b = r.int(a + 1, 9), k = r.int(3, 9); if (gcd(a, b) !== 1) { a = 2; b = 5; } return Q(r, a + ' : ' + b + ' = ? : ' + b * k + ' denk oranında ? yerine hangi sayı gelmelidir?', a * k, [a * k + 1, a + k, b * k - a], 'Payda ' + k + ' ile çarpıldı; pay da ' + k + ' ile çarpılır: ' + a * k); },
     function (r) { var g = r.int(2, 6), a = r.int(1, 4) * g, b = r.int(2, 5) * g; return Q(r, a + ' : ' + b + ' oranını en sade biçimde yazınız.', (a / gcd(a, b)) + ' : ' + (b / gcd(a, b)), [a + ' : ' + b, (b / gcd(a, b)) + ' : ' + (a / gcd(a, b)), (a / gcd(a, b) + 1) + ' : ' + (b / gcd(a, b))], 'EBOB ' + gcd(a, b) + ' ile sadeleştir.'); },
     function (r) { var c = r.pick([['5 cm / 10 cm', 'birimsiz', ['120 km / 2 saat', '300 TL / 3 kg', '6 L / 2 dk']], ['120 km / 2 saat', 'birimli', ['5 cm / 10 cm', '8 kg / 4 kg', '30 TL / 15 TL']]]); var word = c[1]; return Q(r, 'Aşağıdakilerden hangisi ' + (word === 'birimsiz' ? 'birimsiz' : 'birimli') + ' bir orandır?', c[0], c[2], word === 'birimsiz' ? 'Aynı cins nicelikler oranlanınca birim kalmaz.' : 'Farklı cins niceliklerin oranı birimlidir.'); },
     function (r) { var k = r.int(2, 5), a = r.int(3, 4) * k; var tot = a + k * 4; var kiz = 3 * k, erk = 4 * k; return Q(r, 'Bir sınıfta kız : erkek = 3 : 4 ve sınıf mevcudu ' + (kiz + erk) + ' ise kız öğrenci sayısı kaçtır?', kiz, [erk, kiz + 1, kiz + k], 'Toplam parça 7 → 1 parça ' + k + ' → kız 3·' + k + ' = ' + kiz); },
     function (r) { var p = r.pick([[2, 1, 4], [3, 2, 6], [2, 3, 10], [5, 2, 15]]); var res = p[1] * p[2] / p[0]; return Q(r, 'Bir tarifte ' + p[0] + ' bardak un için ' + p[1] + ' bardak süt kullanılıyor. ' + p[2] + ' bardak un için kaç bardak süt gerekir?', N(res), [N(res + 1), N(p[2] - p[0] + p[1]), N(res * 2)], 'Oran ' + p[0] + ' : ' + p[1] + '; ' + p[2] + ' için süt = ' + N(res)); },
     function (r) { var s = r.pick([[50000, 4, '2 km'], [100000, 3, '3 km'], [25000, 8, '2 km'], [50000, 6, '3 km']]); return Q(r, '1 : ' + N(s[0]) + ' ölçekli haritada iki şehir arası ' + s[1] + ' cm ise gerçek uzaklık kaç km’dir?', N(s[0] * s[1] / 100000) + ' km', [N(s[0] * s[1] / 10000) + ' km', N(s[0] * s[1] / 1000000) + ' km', N(s[0] * s[1]) + ' km'], s[1] + ' · ' + N(s[0]) + ' cm = ' + N(s[0] * s[1]) + ' cm = ' + N(s[0] * s[1] / 100000) + ' km'); }]);

  // ============ HAFTA 19 ============
  wk(16, 19, 'Orantı ve Doğru Orantı', 5,
    ['Orantıyı kurar ve çözer.', 'Doğru orantılı nicelikleri tablo ve grafikle gösterir.'],
    [['Ders Açılışı', '<p>1 kalem 3 TL ise 2 kalem 6 TL, 3 kalem 9 TL… Kalem sayısı artarken fiyat nasıl artıyor? Tabloyu çocuk doldursun.</p>'],
     ['Orantı', DEF('İki oranın eşitliğine <b>orantı</b> denir: ' + F('a', 'b') + ' = ' + F('c', 'd') + '. <b>İçler çarpımı = dışlar çarpımı</b>: a·d = b·c.') + EX(F(3, 4) + ' = ' + F('x', 12) + ' → 4x = 36 → x = <b>9</b>')],
     ['Doğru Orantı', DEF('Biri artarken diğeri de <b>aynı kat</b> artıyorsa (veya biri azalırken diğeri aynı kat azalıyorsa) iki nicelik <b>doğru orantılıdır</b>. Oranları (y/x) sabittir: <b>y = k·x</b> (k: orantı sabiti).') + '<table class="tbl"><thead><tr><th>Kalem (x)</th><th>1</th><th>2</th><th>3</th><th>5</th></tr></thead><tbody><tr><td>Fiyat (y)</td><td>3</td><td>6</td><td>9</td><td>15</td></tr></tbody></table><p>y ÷ x = 3 (sabit).</p>'],
     ['Grafik', TIP('Doğru orantının grafiği <b>orijinden (0, 0) geçen bir doğrudur</b>. Orijinden geçmeyen ya da doğru olmayan grafikler doğru orantı değildir.') + ACT('Kareli kâğıtta (x, y) noktalarını işaretleyip birleştirin: (0,0), (1,3), (2,6), (3,9).')]],
    [function (r) { var a = r.int(2, 6), b = r.int(a + 1, 9), k = r.int(2, 6); return Q(r, a + '/' + b + ' = x/' + b * k + ' orantısında x kaçtır?', a * k, [a * k + 1, a + k, b * k - a], 'İçler dışlar çarpımı: x = ' + a + '·' + b * k + ' ÷ ' + b + ' = ' + a * k); },
     function (r) { var k = r.int(2, 8); return Q(r, 'y, x ile doğru orantılıdır ve x = 4 iken y = ' + 4 * k + '. Orantı sabiti (y ÷ x) kaçtır?', k, [k + 1, 4 * k, k - 1 || 2], N(4 * k) + ' ÷ 4 = ' + k); },
     function (r) { var k = r.int(2, 9), x = r.int(6, 12); return Q(r, 'Tabloda x ile y doğru orantılıdır. x = ' + x + ' iken y kaçtır?<br>' + MC.table(['x', '1', '2', '3'], [['y', k, 2 * k, 3 * k]]), k * x, [k * x + k, k + x, k * (x - 1)], 'y = ' + k + '·x → ' + k + '·' + x + ' = ' + k * x); },
     function (r) { var k = r.int(2, 6); var A = [[1, k], [2, 2 * k], [3, 3 * k]], B = [[1, k], [2, 2 * k + 1], [3, 3 * k + 2]]; var fmt = function (a) { return a.map(function (p) { return '(' + p[0] + ', ' + p[1] + ')'; }).join(', '); }; return Q(r, 'Aşağıdaki (x, y) değer çiftlerinden hangisi doğru orantılıdır?', fmt(A), [fmt(B), fmt([[1, k + 2], [2, k + 4], [3, k + 6]]), fmt([[1, k + 1], [2, 2 * k + 3], [3, 3 * k + 4]])], 'y ÷ x her çiftte ' + k + ' (sabit).'); },
     function (r) { return Q(r, 'Doğru orantılı iki niceliğin grafiği için hangisi doğrudur?', 'Orijinden geçen bir doğrudur', ['Orijinden geçmeyen bir doğrudur', 'Eğri bir çizgidir', 'Yatay bir doğrudur'], 'y = kx doğrusu (0, 0) noktasından geçer.'); },
     function (r) { var k = r.pick([2, 3, 4, 5]); return Q(r, 'Doğru orantılı iki nicelikten biri ' + k + ' katına çıkarsa diğeri nasıl değişir?', k + ' katına çıkar', [k + ' azalır', (k + 1) + ' katına çıkar', 'Değişmez'], 'Doğru orantıda iki nicelik aynı kat artar.'); },
     function (r) { var a = r.int(3, 7), b = r.int(2, 9), c = r.int(2, 6); return Q(r, a + '/' + b + ' = ' + (a * c) + '/x orantısında x kaçtır?', b * c, [b * c + 1, a + b + c, b + c], 'Dışlar-içler: ' + a + 'x = ' + a * c * b + ' → x = ' + b * c); },
     function (r) { var k = r.pick([3, 4, 5, 6]); return Q(r, 'x ile y doğru orantılı ve y = ' + k + 'x ise x = 7 iken y kaçtır?', 7 * k, [7 + k, 7 * k + k, k], k + '·7 = ' + 7 * k); }]);

  // ============ HAFTA 20 ============
  wk(16, 20, 'Doğru Orantı Problemleri', 5,
    ['Doğru orantı ile ilgili problemleri çözer.'],
    [['İki Yöntem', '<p><b>Birim orana indirgeme:</b> 5 kg elma 40 TL → 1 kg = 8 TL → 8 kg = 64 TL.<br><b>Orantı kurma:</b> 5/40 = 8/x → x = 64.</p>'],
     ['Örnekler', EX('<b>Hız:</b> Bir araç 3 saatte 240 km gidiyorsa aynı hızla 5 saatte 400 km gider (80 km/saat).<br><b>Tarif:</b> 4 kişilik tarif 300 g un; 10 kişilik → 750 g.<br><b>Yakıt:</b> 100 km’de 7 L yakan araç 250 km’de 17,5 L yakar.')],
     ['Dikkat', WARN('Her ilişki doğru orantı değildir! “İşçi sayısı arttıkça işin bitme süresi azalır” <b>ters orantıdır</b>. Önce niceliklerin birlikte aynı yönde değiştiğini kontrol edin.')],
     ['Etkinlik', ACT('Markette iki farklı boy ürünün birim fiyatını karşılaştırın (1 kg kaç TL?). Hangisi daha ucuz?')]],
    [function (r) { var k = r.pick([5, 8, 10, 12]), a = r.int(2, 6), b = r.int(7, 12); return Q(r, a + ' kg elma ' + N(a * k) + ' TL ise ' + b + ' kg elma kaç TL’dir?', N(b * k), [N(b * k + k), N((a * k) + b), N(b * k - a)], 'Birim fiyat ' + k + ' TL/kg → ' + b + '·' + k + ' = ' + N(b * k)); },
     function (r) { var v = r.pick([60, 70, 80, 90]), t1 = r.int(2, 4), t2 = r.int(5, 8); return Q(r, 'Sabit hızla giden bir araç ' + t1 + ' saatte ' + N(v * t1) + ' km yol alıyor. Aynı hızla ' + t2 + ' saatte kaç km yol alır?', N(v * t2) + ' km', [N(v * t2 + v) + ' km', N(v * t1 + t2) + ' km', N(v * t2 / 2) + ' km'], 'Hız ' + v + ' km/saat → ' + t2 + '·' + v + ' = ' + N(v * t2)); },
     function (r) { var g = r.pick([75, 100, 150]), a = r.pick([2, 4]), b = r.pick([6, 8, 10]); return Q(r, a + ' kişilik bir tarif için ' + a * g + ' g un gerekiyor. ' + b + ' kişilik için kaç g un gerekir?', N(b * g) + ' g', [N((b + 1) * g) + ' g', N(a * g + b) + ' g', N(b * g / 2) + ' g'], 'Kişi başı ' + g + ' g → ' + b + '·' + g + ' = ' + N(b * g)); },
     function (r) { var l = r.pick([7, 6, 8]), km = r.pick([250, 300, 350, 150]); var res = l * km / 100; return Q(r, 'Bir araç 100 km’de ' + l + ' litre yakıt harcıyor. ' + km + ' km’de kaç litre yakıt harcar?', N(res) + ' L', [N(res + l) + ' L', N(l * km) + ' L', N(res / 2) + ' L'], l + '·' + km + ' ÷ 100 = ' + N(res)); },
     function (r) { var p = r.pick([12, 15, 18, 20]), n = r.int(3, 6), m = r.int(7, 12); return Q(r, n + ' defter ' + N(n * p) + ' TL ise ' + m + ' defter kaç TL’dir?', N(m * p), [N(m * p - p), N(n * p + m), N(m * p + p)], 'Bir defter ' + p + ' TL.'); },
     function (r) { var a = r.pick([[4, 30, 10], [3, 12, 9], [2, 10, 6]]); var res = a[1] / a[0] * a[2]; return Q(r, 'Bir musluktan ' + a[0] + ' dakikada ' + a[1] + ' litre su akıyor. Aynı musluktan ' + a[2] + ' dakikada kaç litre su akar?', N(res) + ' L', [N(res + a[1] / a[0]) + ' L', N(a[1] + a[2]) + ' L', N(res * 2) + ' L'], 'Dakikada ' + N(a[1] / a[0]) + ' L → ' + N(res)); },
     function (r) { var c = r.pick([3, 4, 5]), h = r.pick([8, 12, 20]); return Q(r, 'Bir fotokopi makinesi ' + c + ' dakikada ' + c * 10 + ' sayfa çekiyor. ' + h + ' dakikada kaç sayfa çeker?', h * 10, [h * 10 + 10, c + h, h * 5], 'Dakikada 10 sayfa → ' + h * 10); },
     function (r) { return Q(r, 'Aşağıdaki durumlardan hangisi <b>doğru orantı</b> değildir?', 'İşçi sayısı arttıkça işin bitme süresi', ['Alınan kalem sayısı ve ödenen para', 'Gidilen süre ve alınan yol (sabit hızla)', 'Tarifteki kişi sayısı ve un miktarı'], 'İşçi sayısı arttıkça süre azalır; bu ters orantıdır.'); }]);

  // ============ HAFTA 21 ============
  wk(16, 21, 'Yüzde Problemleri, Yüzde Artış ve Azalış', 5,
    ['Yüzde problemlerini çözer.', 'Yüzde artış ve azalışı hesaplar.'],
    [['Hatırlatma', '<p>Yüzde, paydası 100 olan orandır: %25 = 25/100 = 1/4 = 0,25. Çocuğa “yüzde ne işe yarar?” diye sorun: indirim, not, nüfus…</p>'],
     ['Üç Temel Problem', EX('<b>1. Yüzdesi bulma:</b> 80’nin %25’i = 80 · 25/100 = <b>20</b>.<br><b>2. Bütünü bulma:</b> Bir sayının %40’ı 30 ise sayı = 30 · 100/40 = <b>75</b>.<br><b>3. Yüzde bulma:</b> 18, 60’ın yüzde kaçıdır? 18/60 = 30/100 → <b>%30</b>.')],
     ['Yüzde Artış ve Azalış', DEF('<b>Artış yüzdesi</b> = (artış miktarı ÷ eski değer) · 100') + EX('80’den 100’e: artış 20; 20/80 = %25 artış.<br>250’den 200’e: azalış 50; 50/250 = %20 azalış.<br>200 TL’ye %15 zam: 200 · 1,15 = <b>230 TL</b>.') + WARN('Önce %10 artıp sonra %10 azalan değer eski değerine <b>dönmez</b>: 100 → 110 → 99.')],
     ['Etkinlik', ACT('Çocuk bir deneme sınavında doğru sayısının tüm soruya oranını yüzde olarak hesaplasın; iki farklı sınavın yüzdelerini karşılaştırsın.')]],
    [function (r) { var n = r.pick([40, 60, 80, 120, 200, 250]), p = r.pick([10, 20, 25, 30, 40, 50]); return Q(r, N(n) + ' sayısının %' + p + '’i kaçtır?', N(n * p / 100), [N(n * p / 10), N(n * p / 1000 * 10 + p), N(n / p)], n + ' · ' + p + ' ÷ 100 = ' + N(n * p / 100)); },
     function (r) { var p = r.pick([20, 25, 40, 50]), n = r.pick([60, 80, 100, 200]); return Q(r, 'Bir sayının %' + p + '’i ' + N(n * p / 100) + ' ise bu sayı kaçtır?', N(n), [N(n * p / 100 * 2), N(n + p), N(n / 2)], N(n * p / 100) + ' ÷ ' + p + ' · 100 = ' + N(n)); },
     function (r) { var t = r.pick([[18, 60, 30], [15, 50, 30], [12, 40, 30], [9, 30, 30], [24, 80, 30], [35, 70, 50], [21, 28, 75]]); return Q(r, N(t[0]) + ', ' + N(t[1]) + ' sayısının yüzde kaçıdır?', pctStr(t[2]), [pctStr(t[2] + 5), pctStr(t[2] - 5), pctStr(t[0])], t[0] + '/' + t[1] + ' = ' + pctStr(t[2])); },
     function (r) { var a = r.pick([[80, 100, 25], [200, 250, 25], [50, 60, 20], [40, 50, 25], [250, 300, 20]]); return Q(r, 'Bir ürünün fiyatı ' + a[0] + ' TL’den ' + a[1] + ' TL’ye çıkmıştır. Yüzde kaç artmıştır?', pctStr(a[2]), [pctStr(a[2] + 5), pctStr(a[2] - 5), pctStr(a[1] - a[0])], 'Artış ' + (a[1] - a[0]) + '; ' + (a[1] - a[0]) + '/' + a[0] + ' = ' + pctStr(a[2])); },
     function (r) { var a = r.pick([[250, 200, 20], [80, 60, 25], [400, 300, 25], [50, 40, 20], [200, 150, 25]]); return Q(r, 'Bir ürünün fiyatı ' + a[0] + ' TL’den ' + a[1] + ' TL’ye düşmüştür. Yüzde kaç azalmıştır?', pctStr(a[2]), [pctStr(a[2] + 5), pctStr(a[2] - 5), pctStr(a[0] - a[1])], 'Azalış ' + (a[0] - a[1]) + '; ' + (a[0] - a[1]) + '/' + a[0] + ' = ' + pctStr(a[2])); },
     function (r) { var n = r.pick([100, 200, 300, 400, 500]), p = r.pick([10, 15, 20, 25]); return Q(r, N(n) + ' TL’ye %' + p + ' zam yapılırsa yeni fiyat kaç TL olur?', N(n + n * p / 100), [N(n - n * p / 100), N(n * p / 100), N(n + p)], N(n) + ' + ' + N(n * p / 100) + ' = ' + N(n + n * p / 100)); },
     function (r) { var n = r.pick([100, 200, 400]), p = r.pick([10, 20]); var f = n * (1 + p / 100) * (1 - p / 100); return Q(r, N(n) + ' TL’lik bir değer önce %' + p + ' artırılıyor, sonra yeni değer %' + p + ' azaltılıyor. Sonuç kaç TL olur?', N(Math.round(f * 100) / 100), [N(n), N(Math.round(n * (1 + p / 100) * 100) / 100), N(n - p)], 'Önce ' + N(n * (1 + p / 100)) + ', sonra ' + N(Math.round(f * 100) / 100) + '; eski değere dönmez.'); },
     function (r) { var n = r.pick([20, 25, 30, 40]), p = r.pick([20, 40, 60]); return Q(r, 'Bir sınıfta ' + n + ' öğrenci vardır ve öğrencilerin %' + p + '’i kızdır. Kaç erkek öğrenci vardır?', N(n - n * p / 100), [N(n * p / 100), N(n + n * p / 100), N(n - p)], 'Kız ' + N(n * p / 100) + ' → erkek ' + N(n - n * p / 100)); }]);

  // ============ HAFTA 22 ============
  wk(16, 22, 'İndirim, Kâr ve Zarar Problemleri', 5,
    ['İndirim hesaplamalarını yapar.', 'Kâr ve zarar durumlarını yüzde ile hesaplar.'],
    [['Ders Açılışı', '<p>Marketteki “%20 indirim” tabelasını çocuğa gösterin: “400 TL’lik ayakkabıya ne kadar ödeyeceğiz?” İndirimli fiyat ve indirim tutarını tahmin ettirin.</p>'],
     ['İndirim', DEF('İndirim tutarı = etiket fiyatı × indirim oranı; <b>İndirimli fiyat = etiket fiyatı − indirim tutarı</b>.') + EX('400 TL, %25 indirim: indirim 100 TL → 300 TL. (Kısayol: 400 · 0,75 = 300.)<br>%20 indirimle 240 TL ödendi → etiket fiyatı: 240 ÷ 0,8 = <b>300 TL</b>.')],
     ['Kâr ve Zarar', DEF('Satış fiyatı > alış fiyatı → <b>kâr</b> = satış − alış. Satış < alış → <b>zarar</b> = alış − satış. Kâr/zarar yüzdesi <b>alış fiyatına</b> göre hesaplanır.') + EX('Alış 200 TL, %30 kârla satış: 200 · 1,3 = <b>260 TL</b>.<br>Alış 500 TL, %20 zararla satış: 500 · 0,8 = <b>400 TL</b>.<br>Alış 300, satış 360: kâr 60; 60/300 = <b>%20 kâr</b>.')],
     ['Ardışık İndirim', WARN('%20 ve ardından %10 indirim toplam %30 indirim <b>değildir</b>: 100 → 80 → 72 (toplam %28).') + ACT('Çocuk “mağaza” oyunu oynasın: ürün etiketleri yapıp indirim ve kâr hesaplasın; kasada para üstü versin.')]],
    [function (r) { var n = r.pick([200, 300, 400, 500, 800]), p = r.pick([10, 20, 25, 30, 40, 50]); return Q(r, 'Etiket fiyatı ' + N(n) + ' TL olan bir ürüne %' + p + ' indirim yapılırsa indirimli fiyat kaç TL olur?', N(n - n * p / 100), [N(n * p / 100), N(n + n * p / 100), N(n - p)], 'İndirim ' + N(n * p / 100) + ' → ' + N(n - n * p / 100)); },
     function (r) { var a = r.pick([[500, 400, 20], [200, 150, 25], [800, 600, 25], [300, 270, 10], [400, 300, 25]]); return Q(r, a[0] + ' TL’lik bir ürün ' + a[1] + ' TL’ye satılıyor. İndirim oranı yüzde kaçtır?', pctStr(a[2]), [pctStr(a[2] + 5), pctStr(a[2] - 5), pctStr(a[0] - a[1])], 'İndirim ' + (a[0] - a[1]) + '; ' + (a[0] - a[1]) + '/' + a[0] + ' = ' + pctStr(a[2])); },
     function (r) { var p = r.pick([20, 25, 10, 50]), e = r.pick([200, 300, 400, 500]); var pay = e * (100 - p) / 100; return Q(r, '%' + p + ' indirimle ' + N(pay) + ' TL’ye satılan bir ürünün etiket fiyatı kaç TL’dir?', N(e), [N(pay + p), N(pay * 2), N(e + 100)], N(pay) + ' ÷ ' + (100 - p) / 100 + ' = ' + N(e)); },
     function (r) { var a = r.pick([100, 200, 300, 400, 500]), p = r.pick([10, 20, 25, 30, 50]); return Q(r, 'Alış fiyatı ' + N(a) + ' TL olan bir ürün %' + p + ' kârla satılırsa satış fiyatı kaç TL olur?', N(a + a * p / 100), [N(a - a * p / 100), N(a * p / 100), N(a + p)], N(a) + ' + ' + N(a * p / 100) + ' = ' + N(a + a * p / 100)); },
     function (r) { var a = r.pick([200, 300, 400, 500, 1000]), p = r.pick([10, 20, 25]); return Q(r, 'Alış fiyatı ' + N(a) + ' TL olan bir ürün %' + p + ' zararla satılırsa satış fiyatı kaç TL olur?', N(a - a * p / 100), [N(a + a * p / 100), N(a * p / 100), N(a - p)], N(a) + ' − ' + N(a * p / 100) + ' = ' + N(a - a * p / 100)); },
     function (r) { var a = r.pick([[300, 360, 20], [200, 250, 25], [400, 500, 25], [500, 550, 10]]); return Q(r, 'Alış fiyatı ' + a[0] + ' TL, satış fiyatı ' + a[1] + ' TL olan ürünün kâr yüzdesi kaçtır?', pctStr(a[2]), [pctStr(a[2] + 5), pctStr(a[2] - 5), pctStr(a[1] - a[0])], 'Kâr ' + (a[1] - a[0]) + '; ' + (a[1] - a[0]) + '/' + a[0] + ' = ' + pctStr(a[2])); },
     function (r) { var a = r.pick([[80, 68, 15], [200, 170, 15], [100, 90, 10], [50, 40, 20]]); return Q(r, 'Alış fiyatı ' + a[0] + ' TL olan ürün ' + a[1] + ' TL’ye satılıyor. Zarar yüzde kaçtır?', pctStr(a[2]), [pctStr(a[2] + 5), pctStr(a[2] - 5), pctStr(a[0] - a[1])], 'Zarar ' + (a[0] - a[1]) + '; ' + (a[0] - a[1]) + '/' + a[0] + ' = ' + pctStr(a[2])); },
     function (r) { var n = r.pick([100, 200, 500]); var p1 = r.pick([20, 25]), p2 = r.pick([10, 20]); var f = n * (100 - p1) / 100 * (100 - p2) / 100; return Q(r, N(n) + ' TL’lik ürüne önce %' + p1 + ', sonra yeni fiyata %' + p2 + ' indirim yapılıyor. Son fiyat kaç TL’dir?', N(f), [N(n * (100 - p1 - p2) / 100), N(n * (100 - p1) / 100), N(f + 10)], N(n) + ' → ' + N(n * (100 - p1) / 100) + ' → ' + N(f) + ' (toplam indirim %' + N(100 - f * 100 / n) + ')'); }]);
})();
